/* =============================================================================
 * File:   OpcodeDetail.List.cs
 * Author: Cole Tobin
 * =============================================================================
 * Purpose:
 *
 * Lists all the opcodes supported by Sharp86. `GetList()` is generated by
 *   Sharp86.Generator in the repository root.
 * =============================================================================
 * Copyright (c) 2021 Cole Tobin
 *
 * This file is part of Sharp86.
 *
 * Sharp86 is free software: you can redistribute it and/or modify it under the
 *   terms of the GNU General Public License as published by the Free Software
 *   Foundation, either version 3 of the License, or (at your option) any later
 *   version.
 *
 * Sharp86 is distributed in the hope that it will be useful, but WITHOUT ANY
 *   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 *   details.
 *
 * You should have received a copy of the GNU General Public License along with
 *   Sharp86. If not, see <http://www.gnu.org/licenses/>.
 * =============================================================================
 */
using static Sharp86.Cpu.Decoder.Opcode;
using static Sharp86.Cpu.Decoder.OpcodeDetailAttributes;
using Sharp86.Cpu.Instruction;
using static Sharp86.Cpu.IsaExtension;
using System.Collections.ObjectModel;

namespace Sharp86.Cpu.Decoder;
public partial class OpcodeDetail
{
    /// <summary>
    /// A mapping of an <cref>Opcode</cref> to an <cref>OpcodeDetail</cref> object
    /// </summary>
    public static readonly ReadOnlyDictionary<Opcode, OpcodeDetail> List = new(new Dictionary<Opcode, OpcodeDetail>(4096)
    {
        // ABOVE: there's currently about 3700 opcodes; round up to 4096

        { Opcode.Error, new("error", Instruction.Error._, 0) },

        #region 4.. Opcodes
        // 4FMADDPS
        { V4fmaddpsVzHzMxE512, new("v4fmaddps", _4fmaddps.VzHzMxE512, 0, Avx512_4FMAPS) },

        // 4FMADDSS
        { V4fmaddssVzHzMxE, new("v4fmaddss", _4fnmaddss.VzHzMxE, 0, Avx512_4FMAPS) },

        // 4FNMADDPS
        { V4fnmaddpsVzHzMxE512, new("v4fnmaddps", _4fnmaddps.VzHzMxE512, 0, Avx512_4FMAPS) },

        // 4FNMADDSS
        { V4fnmaddssVzHzMxE, new("v4fnmaddss", _4fnmaddss.VzHzMxE, 0, Avx512_4FMAPS) },
        #endregion

        #region A.. Opcodes
        // AAA
        { Opcode.Aaa, new("aaa", Instruction.Aaa._, 0) },

        // AAD
        { AadIb, new("aad", Aad.Ib, 0) },

        // AAM
        { AamIb, new("aam", Aam.Ib, 0) },

        // AAS
        { Opcode.Aas, new("aas", Instruction.Aas._, 0) },

        // ADC
        { AdcALIb, new("adc", Adc.ALIb, 0) }, // acc, imm
        { AdcAXIw, new("adc", Adc.AXIw, 0) },
        { AdcEAXId, new("adc", Adc.EAXId, 0) },
        { AdcRAXId, new("adc", Adc.RAXId, 0) },
        { AdcEbIb, new("adc", Adc.EbIb, Lockable) }, // r/m, imm
        { AdcEwIw, new("adc", Adc.EwIw, Lockable) },
        { AdcEdId, new("adc", Adc.EdId, Lockable) },
        { AdcEqId, new("adc", Adc.EqId, Lockable) },
        { AdcEwIb, new("adc", Adc.EwIb, Lockable) }, // r/m, imm8
        { AdcEdIb, new("adc", Adc.EdIb, Lockable) },
        { AdcEqIb, new("adc", Adc.EqIb, Lockable) },
        { AdcEbGb, new("adc", Adc.EbGb, Lockable) }, // r/m, reg
        { AdcEwGw, new("adc", Adc.EwGw, Lockable) },
        { AdcEdGd, new("adc", Adc.EdGd, Lockable) },
        { AdcEqGq, new("adc", Adc.EqGq, Lockable) },
        { AdcGbEb, new("adc", Adc.GbEb, 0) }, // reg, r/m
        { AdcGwEw, new("adc", Adc.GwEw, 0) },
        { AdcGdEd, new("adc", Adc.GdEd, 0) },
        { AdcGqEq, new("adc", Adc.GqEq, 0) },

        // ADCX
        { AdcxGdEd, new("adcx", Adcx.GdEd, 0, Adx) },
        { AdcxGqEq, new("adcx", Adcx.GqEq, 0, Adx) },

        // ADD
        { AddALIb, new("add", Add.ALIb, 0) }, // acc, imm
        { AddAXIw, new("add", Add.AXIw, 0) },
        { AddEAXId, new("add", Add.EAXId, 0) },
        { AddRAXId, new("add", Add.RAXId, 0) },
        { AddEbIb, new("add", Add.EbIb, Lockable) }, // r/m, imm
        { AddEwIw, new("add", Add.EwIw, Lockable) },
        { AddEdId, new("add", Add.EdId, Lockable) },
        { AddEqId, new("add", Add.EqId, Lockable) },
        { AddEwIb, new("add", Add.EwIb, Lockable) }, // r/m, imm8
        { AddEdIb, new("add", Add.EdIb, Lockable) },
        { AddEqIb, new("add", Add.EqIb, Lockable) },
        { AddEbGb, new("add", Add.EbGb, Lockable) }, // r/m, reg
        { AddEwGw, new("add", Add.EwGw, Lockable) },
        { AddEdGd, new("add", Add.EdGd, Lockable) },
        { AddEqGq, new("add", Add.EqGq, Lockable) },
        { AddGbEb, new("add", Add.GbEb, 0) }, // reg, r/m
        { AddGwEw, new("add", Add.GwEw, 0) },
        { AddGdEd, new("add", Add.GdEd, 0) },
        { AddGqEq, new("add", Add.GqEq, 0) },

        // ADDPD
        { AddpdVxWx, new("addpd", Addpd.VxWx, 0, Sse2) },
        { VaddpdVxHxWxV128, new("vaddpd", Addpd.VxHxWxV128, 0, Avx) },
        { VaddpdVyHyWyV256, new("vaddpd", Addpd.VyHyWyV256, 0, Avx) },
        { VaddpdVxHxWxE128, new("vaddpd", Addpd.VxHxWxE128, 0, Avx512_VL) },
        { VaddpdVyHyWyE256, new("vaddpd", Addpd.VyHyWyE256, 0, Avx512_VL) },
        { VaddpdVzHzWzE512, new("vaddpd", Addpd.VzHzWzE512, 0, Avx512_F) },

        // ADDPS
        { AddpsVxWx, new("addpd", Addps.VxWx, 0, Sse) },
        { VaddpsVxHxWxV128, new("vaddps", Addps.VxHxWxV128, 0, Avx) },
        { VaddpsVyHyWyV256, new("vaddps", Addps.VyHyWyV256, 0, Avx) },
        { VaddpsVxHxWxE128, new("vaddps", Addps.VxHxWxE128, 0, Avx512_VL) },
        { VaddpsVyHyWyE256, new("vaddps", Addps.VyHyWyE256, 0, Avx512_VL) },
        { VaddpsVzHzWzE512, new("vaddps", Addps.VzHzWzE512, 0, Avx512_F) },

        // ADDSD
        { AddsdVxWx, new("addsd", Addsd.VxWx, 0, Sse2) },
        { VaddsdVxHxWxV, new("vaddsd", Addsd.VxHxWxV, 0, Avx) },
        { VaddsdVxHxWxE, new("vaddsd", Addsd.VxHxWxE, 0, Avx512_F) },

        // ADDSD
        { AddssVxWx, new("addss", Addss.VxWx, 0, Sse) },
        { VaddssVxHxWxV, new("vaddss", Addss.VxHxWxV, 0, Avx) },
        { VaddssVxHxWxE, new("vaddss", Addss.VxHxWxE, 0, Avx512_F) },

        // ADDSUBPD
        { AddsubpdVxWx, new("addsubpd", Addsubpd.VxWx, 0, Sse3) },
        { VaddsubpdVxHxWxV128, new("vaddsubpd", Addsubpd.VxHxWxV128, 0, Avx) },
        { VaddsubpdVyHyWyV256, new("vaddsubpd", Addsubpd.VyHyWyV256, 0, Avx) },

        // ADOX
        { AdoxGdEd, new("adox", Adox.GdEd, 0, Adx) },
        { AdoxGqEq, new("adox", Adox.GqEq, 0, Adx) },

        // AESDEC
        { AesdecVxWx, new("aesdec", Aesdec.VxWx, 0, AesNI) },
        { VaesdecVxHxWxV128, new("vaesdec", Aesdec.VxHxWxV128, 0, Avx, AesNI) },
        { VaesdecVyHyWyV256, new("vaesdec", Aesdec.VyHyWyV256, 0, Avx, Vaes) },
        { VaesdecVxHxWxE128, new("vaesdec", Aesdec.VxHxWxE128, 0, Avx512_VL, AesNI) },
        { VaesdecVyHyWyE256, new("vaesdec", Aesdec.VyHyWyE256, 0, Avx512_VL, AesNI) },
        { VaesdecVzHzWzE512, new("vaesdec", Aesdec.VzHzWzE512, 0, Avx512_F, AesNI) },

        // AESDEC128KL
        // TODO: Prepare attribute?
        { Aesdec128klVxM, new("aesdec128kl", Aesdec128kl.VxM, 0, AesKle) },

        // AESDEC256KL
        // TODO: Prepare attribute?
        { Aesdec256klVxMz, new("aesdec256kl", Aesdec256kl.VxMz, 0, AesKle) },

        // AESDECLAST
        { AesdeclastVxWx, new("aesdeclast", Aesdeclast.VxWx, 0, AesNI) },
        { VaesdeclastVxHxWxV128, new("vaesdeclast", Aesdeclast.VxHxWxV128, 0, Avx, AesNI) },
        { VaesdeclastVyHyWyV256, new("vaesdeclast", Aesdeclast.VyHyWyV256, 0, Avx, Vaes) },
        { VaesdeclastVxHxWxE128, new("vaesdeclast", Aesdeclast.VxHxWxE128, 0, Avx512_VL, AesNI) },
        { VaesdeclastVyHyWyE256, new("vaesdeclast", Aesdeclast.VyHyWyE256, 0, Avx512_VL, AesNI) },
        { VaesdeclastVzHzWzE512, new("vaesdeclast", Aesdeclast.VzHzWzE512, 0, Avx512_F, AesNI) },

        // AESDECWIDE128KL
        // TODO: Prepare attribute?
        { Aesdecwide128klM, new("Aesdecwide128kl", Aesdecwide128kl.M, 0, AesKle) },

        // AESDECWIDE256KL
        // TODO: Prepare attribute?
        { Aesdecwide256klMz, new("aesdecwide256kl", Aesdecwide256kl.Mz, 0, AesKle) },

        // AESENC
        { AesencVxWx, new("aesenc", Aesenc.VxWx, 0, AesNI) },
        { VaesencVxHxWxV128, new("vaesenc", Aesenc.VxHxWxV128, 0, Avx, AesNI) },
        { VaesencVyHyWyV256, new("vaesenc", Aesenc.VyHyWyV256, 0, Avx, Vaes) },
        { VaesencVxHxWxE128, new("vaesenc", Aesenc.VxHxWxE128, 0, Avx512_VL, Vaes) },
        { VaesencVyHyWyE256, new("vaesenc", Aesenc.VyHyWyE256, 0, Avx512_VL, Vaes) },
        { VaesencVzHzWzE512, new("vaesenc", Aesenc.VzHzWzE512, 0, Avx512_F, Vaes) },

        // AESENC128KL
        // TOOD: Prepare attribute?
        { Aesenc128klVxM, new("aesenc128kl", Aesenc128kl.VxM, 0, AesKle) },

        // AESENC256KL
        // TOOD: Prepare attribute?
        { Aesenc256klVxMz, new("aesenc256kl", Aesenc256kl.VxMz, 0, AesKle) },

        // AESENCLAST
        { AesenclastVxWx, new("aesenclast", Aesenclast.VxWx, 0, AesNI) },
        { VaesenclastVxHxWxV128, new("vaesenclast", Aesenclast.VxHxWxV128, 0, Avx, AesNI) },
        { VaesenclastVyHyWyV256, new("vaesenclast", Aesenclast.VyHyWyV256, 0, Avx, Vaes) },
        { VaesenclastVxHxWxE128, new("vaesenclast", Aesenclast.VxHxWxE128, 0, Avx512_VL, Vaes) },
        { VaesenclastVyHyWyE256, new("vaesenclast", Aesenclast.VyHyWyE256, 0, Avx512_VL, Vaes) },
        { VaesenclastVzHzWzE512, new("vaesenclast", Aesenclast.VzHzWzE512, 0, Avx512_F, Vaes) },

        // AESENCWIDE128KL
        // TODO: Prepare attribute?
        { Aesencwide128klM, new("aesencwide128kl", Aesencwide128kl.M, 0, AesKle) },

        // AESENCWIDE256KL
        // TODO: Prepare attribute?
        { Aesencwide256klMz, new("aesencwide256kl", Aesencwide256kl.Mz, 0, AesKle) },

        // AESIMC
        { AesimcVxWx, new("aesimc", Aesimc.VxWx, 0, AesNI) },
        { VaesimcVxWxV128, new("vaesimc", Aesimc.VxWxV128, 0, Avx) },

        // AESKEYGENASSIST
        { AeskeygenassistVxWxIb, new("aeskeygenassist", Aeskeygenassist.VxWxIb, 0, AesNI) },
        { VaeskeygenassistVxWxIbV128, new("vaeskeygenassist", Aeskeygenassist.VxWxIbV128, 0, Avx) },

        // AND
        { AndALIb, new("and", And.ALIb, 0) }, // acc, imm
        { AndAXIw, new("and", And.AXIw, 0) },
        { AndEAXId, new("and", And.EAXId, 0) },
        { AndRAXId, new("and", And.RAXId, 0) },
        { AndEbIb, new("and", And.EbIb, Lockable) }, // r/m, imm
        { AndEwIw, new("and", And.EwIw, Lockable) },
        { AndEdId, new("and", And.EdId, Lockable) },
        { AndEqId, new("and", And.EqId, Lockable) },
        { AndEwIb, new("and", And.EwIb, Lockable) }, // r/m, imm8
        { AndEdIb, new("and", And.EdIb, Lockable) },
        { AndEqIb, new("and", And.EqIb, Lockable) },
        { AndEbGb, new("and", And.EbGb, Lockable) }, // r/m, reg
        { AndEwGw, new("and", And.EwGw, Lockable) },
        { AndEdGd, new("and", And.EdGd, Lockable) },
        { AndEqGq, new("and", And.EqGq, Lockable) },
        { AndGbEb, new("and", And.GbEb, 0) }, // reg, r/m
        { AndGwEw, new("and", And.GwEw, 0) },
        { AndGdEd, new("and", And.GdEd, 0) },
        { AndGqEq, new("and", And.GqEq, 0) },

        // ANDN
        { AndnGdBdEd, new("andn", Andn.GdBdEd, 0, Bmi1) },
        { AndnGqBqEq, new("andn", Andn.GqBqEq, 0, Bmi1) },

        // ALIGND
        { ValigndVxHxWxIbE128, new("valignd", Alignd.VxHxWxIbE128, 0, Avx512_VL) },
        { ValigndVyHyWyIbE256, new("valignd", Alignd.VyHyWyIbE256, 0, Avx512_VL) },
        { ValigndVzHzWzIbE512, new("valignd", Alignd.VzHzWzIbE512, 0, Avx512_F) },

        // ALIGNQ
        { ValignqVxHxWxIbE128, new("valignq", Alignq.VxHxWxIbE128, 0, Avx512_VL) },
        { ValignqVyHyWyIbE256, new("valignq", Alignq.VyHyWyIbE256, 0, Avx512_VL) },
        { ValignqVzHzWzIbE512, new("valignq", Alignq.VzHzWzIbE512, 0, Avx512_F) },

        // ANDPD
        { AndpdVxWx, new("andpd", Andpd.VxWx, 0, Sse2) },
        { VandpdVxHxWxV128, new("vandpd", Andpd.VxHxWxV128, 0, Avx) },
        { VandpdVyHyWyV256, new("vandpd", Andpd.VyHyWyV256, 0, Avx) },
        { VandpdVxHxWxE128, new("vandpd", Andpd.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandpdVyHyWyE256, new("vandpd", Andpd.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandpdVzHzWzE512, new("vandpd", Andpd.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ANDPS
        { AndpsVxWx, new("andps", Andps.VxWx, 0, Sse) },
        { VandpsVxHxWxV128, new("vandps", Andps.VxHxWxV128, 0, Avx) },
        { VandpsVyHyWyV256, new("vandps", Andps.VyHyWyV256, 0, Avx) },
        { VandpsVxHxWxE128, new("vandps", Andps.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandpsVyHyWyE256, new("vandps", Andps.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandpsVzHzWzE512, new("vandps", Andps.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ANDNPD
        { AndnpdVxWx, new("andnpd", Andnpd.VxWx, 0, Sse2) },
        { VandnpdVxHxWxV128, new("vandnpd", Andnpd.VxHxWxV128, 0, Avx) },
        { VandnpdVyHyWyV256, new("vandnpd", Andnpd.VyHyWyV256, 0, Avx) },
        { VandnpdVxHxWxE128, new("vandnpd", Andnpd.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandnpdVyHyWyE256, new("vandnpd", Andnpd.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandnpdVzHzWzE512, new("vandnpd", Andnpd.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ANDNPS
        { AndnpsVxWx, new("andnps", Andnps.VxWx, 0, Sse) },
        { VandnpsVxHxWxV128, new("vandnps", Andnps.VxHxWxV128, 0, Avx) },
        { VandnpsVyHyWyV256, new("vandnps", Andnps.VyHyWyV256, 0, Avx) },
        { VandnpsVxHxWxE128, new("vandnps", Andnps.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandnpsVyHyWyE256, new("vandnps", Andnps.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandnpsVzHzWzE512, new("vandnps", Andnps.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ARPL
        { ArplEwGw, new("arpl", Arpl.EwGw, 0) },
        #endregion

        #region B.. Opcodes
        // BEXTR
        { BextrGdEdBd, new("bextr", Bextr.GdEdBd, 0, Bmi1) },
        { BextrGqEqBq, new("bextr", Bextr.GqEqBq, 0, Bmi1) },

        // BLENDMPD
        { VblendmpdVxHxWxE128, new("vblendmpd", Blendmpd.VxHxWxE128, 0, Avx512_VL) },
        { VblendmpdVyHyWyE256, new("vblendmpd", Blendmpd.VyHyWyE256, 0, Avx512_VL) },
        { VblendmpdVzHzWzE512, new("vblendmpd", Blendmpd.VzHzWzE512, 0, Avx512_F) },

        // BLENDMPS
        { VblendmpsVxHxWxE128, new("vblendmps", Blendmps.VxHxWxE128, 0, Avx512_VL) },
        { VblendmpsVyHyWyE256, new("vblendmps", Blendmps.VyHyWyE256, 0, Avx512_VL) },
        { VblendmpsVzHzWzE512, new("vblendmps", Blendmps.VzHzWzE512, 0, Avx512_F) },

        // BLENDPD
        { BlendpdVxWxIb, new("blendpd", Blendpd.VxWxIb, 0, Sse4_1) },
        { VblendpdVxHxWxIbV128, new("vblendpd", Blendpd.VxHxWxIbV128, 0, Avx) },
        { VblendpdVyHyWyIbV256, new("vblendpd", Blendpd.VyHyWyIbV256, 0, Avx) },

        // BLENDPS
        { BlendpsVxWxIb, new("blendps", Blendps.VxWxIb, 0, Sse4_1) },
        { VblendpsVxHxWxIbV128, new("vblendps", Blendps.VxHxWxIbV128, 0, Avx) },
        { VblendpsVyHyWyIbV256, new("vblendps", Blendps.VyHyWyIbV256, 0, Avx) },

        // BLENDVPD
        { BlendvpdVxWx, new("blendvpd", Blendvpd.VxWx, 0, Sse4_1) },
        { VblendvpdVxHxWxLxV128, new("vblendvpd", Blendvpd.VxHxWxLxV128, 0, Avx) },
        { VblendvpdVyHyWyLyV256, new("vblendvpd", Blendvpd.VyHyWyLyV256, 0, Avx) },

        // BLENDVPS
        { BlendvpsVxWx, new("blendvps", Blendvps.VxWx, 0, Sse4_1) },
        { VblendvpsVxHxWxLxV128, new("vblendvps", Blendvps.VxHxWxLxV128, 0, Avx) },
        { VblendvpsVyHyWyLyV256, new("vblendvps", Blendvps.VyHyWyLyV256, 0, Avx) },

        // BLSI
        { BlsiBdEd, new("blsi", Blsi.BdEd, 0, Bmi1) },
        { BlsiBqEq, new("blsi", Blsi.BqEq, 0, Bmi1) },

        // BLSMSK
        { BlsmskBdEd, new("blsmsk", Blsmsk.BdEd, 0, Bmi1) },
        { BlsmskBqEq, new("blsmsk", Blsmsk.BqEq, 0, Bmi1) },

        // BLSR
        { BlsrBdEd, new("blsr", Blsr.BdEd, 0, Bmi1) },
        { BlsrBqEq, new("blsr", Blsr.BqEq, 0, Bmi1) },

        // BNDCL
        { BndclBGxEd, new("bndcl", Bndcl.BGxEd, 0, Mpx) },
        { BndclBGxEq, new("bndcl", Bndcl.BGxEq, 0, Mpx) },

        // BNDCU
        { BndcuBGxEd, new("bndcu", Bndcu.BGxEd, 0, Mpx) },
        { BndcuBGxEq, new("bndcu", Bndcu.BGxEq, 0, Mpx) },

        // BNDCN
        { BndcnBGxEd, new("bndcn", Bndcn.BGxEd, 0, Mpx) },
        { BndcnBGxEq, new("bndcn", Bndcn.BGxEq, 0, Mpx) },

        // BNDLDX
        { BndldxBGxM, new("bndldx", Bndldx.BGxM, 0, Mpx) },

        // BNDMK
        { BndmkBGxMd, new("bndmk", Bndmk.BGxMd, 0, Mpx) },
        { BndmkBGxMq, new("bndmk", Bndmk.BGxMq, 0, Mpx) },

        // BNDMOV
        { BndmovBGxBEq, new("bndmov", Bndmov.BGxBEq, 0, Mpx) },
        { BndmovBGxBEx, new("bndmov", Bndmov.BGxBEx, 0, Mpx) },
        { BndmovBEqBGx, new("bndmov", Bndmov.BEqBGx, 0, Mpx) },
        { BndmovBExBGx, new("bndmov", Bndmov.BExBGx, 0, Mpx) },

        // BNDSTX
        { BndstxMBGx, new("bndstx", Bndstx.MBGx, 0, Mpx) },

        // BOUND
        { BoundGwMd, new("bound", Bound.GwMd, 0) },
        { BoundGdMq, new("bound", Bound.GdMq, 0) },

        // BROADCASTx (VEX)
        { Vbroadcastf128VyMxV256, new("vbroadcastf128", Broadcastf128.VyMxV256, 0, Avx) }, // ..F128
        { VbroadcastsdVyMqV256, new("vbroadcastsd", Broadcastsd.VyMqV256, 0, Avx) }, // ..SD
        { VbroadcastsdVyUxV256, new("vbroadcastsd", Broadcastsd.VyUxV256, 0, Avx2) },
        { VbroadcastssVxMdV128, new("vbroadcastss", Broadcastss.VxMdV128, 0, Avx) }, // ..SS
        { VbroadcastssVyMdV256, new("vbroadcastss", Broadcastss.VyMdV256, 0, Avx) },
        { VbroadcastssVxUxV128, new("vbroadcastss", Broadcastss.VxUxV128, 0, Avx2) },
        { VbroadcastssVyUxV256, new("vbroadcastss", Broadcastss.VyUxV256, 0, Avx2) },
        // BROADCASTx (EVEX)
        // TODO:  Do `F32X4` and `F64X4` need `Avx512_DQ`?
        { Vbroadcastf32x2VyWxE256, new("vbroadcastf32x2", Broadcastf32x2.VyWxE256, 0, Avx512_VL, Avx512_DQ) }, // ..F32X2
        { Vbroadcastf32x2VzWxE512, new("vbroadcastf32x2", Broadcastf32x2.VzWxE512, 0, Avx512_F, Avx512_DQ) },
        { Vbroadcastf32x4VyMxE256, new("vbroadcastf32x4", Broadcastf32x4.VyMxE256, 0, Avx512_VL) }, // ..F32X4
        { Vbroadcastf32x4VzMxE512, new("vbroadcastf32x4", Broadcastf32x4.VzMxE512, 0, Avx512_F) },
        { Vbroadcastf32x8VzMyE512, new("vbroadcastf32x8", Broadcastf32x8.VzMyE512, 0, Avx512_F, Avx512_DQ) }, // ..F32X8
        { Vbroadcastf64x2VyMxE256, new("vbroadcastf64x2", Broadcastf64x2.VyMxE256, 0, Avx512_VL, Avx512_DQ) }, // ..F64X2
        { Vbroadcastf64x2VzMxE512, new("vbroadcastf64x2", Broadcastf64x2.VzMxE512, 0, Avx512_F, Avx512_DQ) },
        { Vbroadcastf64x4VzMyE512, new("vbroadcastf64x4", Broadcastf64x4.VzMyE512, 0, Avx512_F) }, // ..F64X4
        { VbroadcastsdVyWxE256, new("vbroadcastsd", Broadcastsd.VyWxE256, 0, Avx512_VL) }, // ..SD
        { VbroadcastsdVzWxE512, new("vbroadcastsd", Broadcastsd.VzWxE512, 0, Avx512_F) },
        { VbroadcastssVxWxE128, new("vbroadcastss", Broadcastss.VxWxE128, 0, Avx512_VL) }, // ..SS
        { VbroadcastssVyWxE256, new("vbroadcastss", Broadcastss.VyWxE256, 0, Avx512_VL) },
        { VbroadcastssVzWxE512, new("vbroadcastss", Broadcastss.VzWxE512, 0, Avx512_F) },

        // BSF
        { BsfGwEw, new("bsf", Bsf.GwEw, 0) },
        { BsfGdEd, new("bsf", Bsf.GdEd, 0) },
        { BsfGqEq, new("bsf", Bsf.GqEq, 0) },

        // BSR
        { BsrGwEw, new("bsr", Bsr.GwEw, 0) },
        { BsrGdEd, new("bsr", Bsr.GdEd, 0) },
        { BsrGqEq, new("bsr", Bsr.GqEq, 0) },

        // BSWAP
        { BswapZw, new("bswap", Bswap.Zw, 0) },
        { BswapZd, new("bswap", Bswap.Zd, 0) },
        { BswapZq, new("bswap", Bswap.Zq, 0) },

        // BT
        { BtEwGw, new("bt", Bt.EwGw, 0) },
        { BtEdGd, new("bt", Bt.EdGd, 0) },
        { BtEqGq, new("bt", Bt.EqGq, 0) },
        { BtEwIb, new("bt", Bt.EwIb, 0) },
        { BtEdIb, new("bt", Bt.EdIb, 0) },
        { BtEqIb, new("bt", Bt.EqIb, 0) },

        // BTC
        { BtcEwGw, new("btc", Btc.EwGw, 0) },
        { BtcEdGd, new("btc", Btc.EdGd, 0) },
        { BtcEqGq, new("btc", Btc.EqGq, 0) },
        { BtcEwIb, new("btc", Btc.EwIb, 0) },
        { BtcEdIb, new("btc", Btc.EdIb, 0) },
        { BtcEqIb, new("btc", Btc.EqIb, 0) },

        // BTR
        { BtrEwGw, new("btr", Btr.EwGw, 0) },
        { BtrEdGd, new("btr", Btr.EdGd, 0) },
        { BtrEqGq, new("btr", Btr.EqGq, 0) },
        { BtrEwIb, new("btr", Btr.EwIb, 0) },
        { BtrEdIb, new("btr", Btr.EdIb, 0) },
        { BtrEqIb, new("btr", Btr.EqIb, 0) },

        // BTS
        { BtsEwGw, new("bts", Bts.EwGw, 0) },
        { BtsEdGd, new("bts", Bts.EdGd, 0) },
        { BtsEqGq, new("bts", Bts.EqGq, 0) },
        { BtsEwIb, new("bts", Bts.EwIb, 0) },
        { BtsEdIb, new("bts", Bts.EdIb, 0) },
        { BtsEqIb, new("bts", Bts.EqIb, 0) },

        // BZHI
        { BzhiGdEdBd, new("bzhi", Bzhi.GdEdBd, 0, Bmi2) },
        { BzhiGqEqBq, new("bzhi", Bzhi.GqEqBq, 0, Bmi2) },
        #endregion

        #region C.. Opcodes
        // CALL
        { CallJw, new("call", Call.Jw, 0) },
        { CallJd, new("call", Call.Jd, 0) },
        { CallEw, new("call", Call.Ew, 0) },
        { CallEd, new("call", Call.Ed, 0) },
        { CallEq, new("call", Call.Eq, 0) },
        // CALLF
        { CallApww, new("callf", Call.Apww, 0) },
        { CallApwd, new("callf", Call.Apwd, 0) },
        { CallMpww, new("callf", Call.Mpww, 0) },
        { CallMpwd, new("callf", Call.Mpwd, 0) },
        { CallMpwq, new("callf", Call.Mpwq, 0) },

        // CBW / CWDE / CDQE
        { Opcode.Cbw, new("cbw", Instruction.Cbw._, 0) },
        { Opcode.Cwde, new("cwde", Instruction.Cwde._, 0) },
        { Opcode.Cdqe, new("cdqe", Instruction.Cdqe._, 0) },

        // CLAC
        { Opcode.Clac, new("clac", Instruction.Clac._, 0, Smap) },

        // CLC
        { Opcode.Clc, new("clc", Instruction.Clc._, 0) },

        // CLD
        { Opcode.Cld, new("cld", Instruction.Cld._, 0) },

        // CLDEMOTE
        { CldemoteMb, new("cldemote", Instruction.Cldemote.Mb, 0, IsaExtension.Cldemote) },

        // CLFLUSH
        { ClflushMb, new("clflush", Clflush.Mb, 0, Clfsh) },

        // CLFLUSHOPT
        { ClflushoptMb, new("clflushopt", Instruction.Clflushopt.Mb, 0, IsaExtension.Clflushopt) },

        // CLI
        { Opcode.Cli, new("cli", Instruction.Cli._, 0) },

        // CLRSSBSY
        { ClrssbsyMq, new("clrssbsy", Clrssbsy.Mq, 0, CetSS) },

        // CLTS
        { Opcode.Clts, new("clts", Instruction.Clts._, 0) },

        // CLUI
        { Opcode.Clui, new("clui", Instruction.Clui._, 0, Uintr) },

        // CLWB
        { ClwbMb, new("clwb", Instruction.Clwb.Mb, 0, IsaExtension.Clwb) },

        // CMC
        { Opcode.Cmc, new("cmc", Instruction.Cmc._, 0) },

        // CMOVcc
        { CmovccGwEw, new("cmovCC", Cmovcc.GwEw, 0) },
        { CmovccGdEd, new("cmovCC", Cmovcc.GdEd, 0) },
        { CmovccGqEq, new("cmovCC", Cmovcc.GqEq, 0) },

        // CMP
        { CmpALIb, new("cmp", Cmp.ALIb, 0) }, // acc, imm
        { CmpAXIw, new("cmp", Cmp.AXIw, 0) },
        { CmpEAXId, new("cmp", Cmp.EAXId, 0) },
        { CmpRAXId, new("cmp", Cmp.RAXId, 0) },
        { CmpEbIb, new("cmp", Cmp.EbIb, 0) }, // r/m, imm
        { CmpEwIw, new("cmp", Cmp.EwIw, 0) },
        { CmpEdId, new("cmp", Cmp.EdId, 0) },
        { CmpEqId, new("cmp", Cmp.EqId, 0) },
        { CmpEwIb, new("cmp", Cmp.EwIb, 0) }, // r/m, imm8
        { CmpEdIb, new("cmp", Cmp.EdIb, 0) },
        { CmpEqIb, new("cmp", Cmp.EqIb, 0) },
        { CmpEbGb, new("cmp", Cmp.EbGb, 0) }, // r/m, reg
        { CmpEwGw, new("cmp", Cmp.EwGw, 0) },
        { CmpEdGd, new("cmp", Cmp.EdGd, 0) },
        { CmpEqGq, new("cmp", Cmp.EqGq, 0) },
        { CmpGbEb, new("cmp", Cmp.GbEb, 0) }, // reg, r/m
        { CmpGwEw, new("cmp", Cmp.GwEw, 0) },
        { CmpGdEd, new("cmp", Cmp.GdEd, 0) },
        { CmpGqEq, new("cmp", Cmp.GqEq, 0) },

        // CMPPD
        { CmppdVxWxIb, new("cmppd", Cmppd.VxWxIb, 0, Sse2) },
        { VcmppdVxHxWxIbV128, new("vcmppd", Cmppd.VxHxWxIbV128, 0, Avx) },
        { VcmppdVyHyWyIbV256, new("vcmppd", Cmppd.VyHyWyIbV256, 0, Avx) },
        { VcmppdKGqHxWxIbE128, new("vcmppd", Cmppd.KGqHxWxIbE128, 0, Avx512_VL) },
        { VcmppdKGqHyWyIbE256, new("vcmppd", Cmppd.KGqHyWyIbE256, 0, Avx512_VL) },
        { VcmppdKGqHzWzIbE512, new("vcmppd", Cmppd.KGqHzWzIbE512, 0, Avx512_F) },

        // CMPPS
        { CmppsVxWxIb, new("cmpps", Cmpps.VxWxIb, 0, Sse) },
        { VcmppsVxHxWxIbV128, new("vcmpps", Cmpps.VxHxWxIbV128, 0, Avx) },
        { VcmppsVyHyWyIbV256, new("vcmpps", Cmpps.VyHyWyIbV256, 0, Avx) },
        { VcmppsKGqHxWxIbE128, new("vcmpps", Cmpps.KGqHxWxIbE128, 0, Avx512_VL) },
        { VcmppsKGqHyWyIbE256, new("vcmpps", Cmpps.KGqHyWyIbE256, 0, Avx512_VL) },
        { VcmppsKGqHzWzIbE512, new("vcmpps", Cmpps.KGqHzWzIbE512, 0, Avx512_F) },

        // CMPS
        { Opcode.Cmpsb, new("cmpsb", Instruction.Cmpsb._, 0) },
        { Opcode.Cmpsw, new("cmpsw", Instruction.Cmpsw._, 0) },
        { Opcode.Cmpsd, new("cmpsd", Instruction.Cmpsd._, 0) },
        { Opcode.Cmpsq, new("cmpsq", Instruction.Cmpsq._, 0) },

        // CMPSD
        { CmpsdVxWxIb, new("cmpsd", Instruction.Cmpsd.VxWxIb, 0, Sse2) },
        { VcmpsdVxHxWxIbV, new("vcmpsd", Instruction.Cmpsd.VxHxWxIbV, 0, Avx) },
        { VcmpsdKGqHxWxIbE, new("vcmpsd", Instruction.Cmpsd.KGqHxWxIbE, 0, Avx512_F) },

        // CMPSS
        { CmpssVxWxIb, new("cmpss", Cmpss.VxWxIb, 0, Sse) },
        { VcmpssVxHxWxIbV, new("vcmpss", Cmpss.VxHxWxIbV, 0, Avx) },
        { VcmpssKGqHxWxIbE, new("vcmpss", Cmpss.KGqHxWxIbE, 0, Avx512_F) },

        // CMPXCHG
        { CmpxchgEbGb, new("cmpxchg", Cmpxchg.EbGb, 0) },
        { CmpxchgEwGw, new("cmpxchg", Cmpxchg.EwGw, 0) },
        { CmpxchgEdGd, new("cmpxchg", Cmpxchg.EdGd, 0) },
        { CmpxchgEqGq, new("cmpxchg", Cmpxchg.EqGq, 0) },

        // CMPXCHG8B / CMPXCHG16B
        { Cmpxchg8bMq, new("cmpxchg8b", Cmpxchg8b.Mq, 0) },
        { Cmpxchg16bMx, new("cmpxchg16b", Instruction.Cmpxchg16b.Mx, 0, IsaExtension.Cmpxchg16b) },

        // COMISD
        { ComisdVxWx, new("comisd", Comisd.VxWx, 0, Sse2) },
        { VcomisdVxWxV, new("vcomisd", Comisd.VxWxV, 0, Avx) },
        { VcomisdVxWxE, new("vcomisd", Comisd.VxWxE, 0, Avx512_F) },

        // COMISS
        { ComissVxWx, new("comiss", Comiss.VxWx, 0, Sse) },
        { VcomissVxWxV, new("vcomiss", Comiss.VxWxV, 0, Avx) },
        { VcomissVxWxE, new("vcomiss", Comiss.VxWxE, 0, Avx512_F) },

        // COMPRESSPD
        { VcompresspdWxVxE128, new("vcompresspd", Compresspd.WxVxE128, 0, Avx512_VL) },
        { VcompresspdWyVyE256, new("vcompresspd", Compresspd.WyVyE256, 0, Avx512_VL) },
        { VcompresspdWzVzE512, new("vcompresspd", Compresspd.WzVzE512, 0, Avx512_F) },

        // COMPRESSPS
        { VcompresspsWxVxE128, new("vcompressps", Compressps.WxVxE128, 0, Avx512_VL) },
        { VcompresspsWyVyE256, new("vcompressps", Compressps.WyVyE256, 0, Avx512_VL) },
        { VcompresspsWzVzE512, new("vcompressps", Compressps.WzVzE512, 0, Avx512_F) },

        // CPUID
        { Opcode.Cpuid, new("cpuid", Instruction.Cpuid._, 0) },

        // CRC32
        { Crc32GdEb, new("crc32", Crc32.GdEb, 0, Sse4_2) },
        { Crc32GqEb, new("crc32", Crc32.GqEb, 0, Sse4_2) },
        { Crc32GdEw, new("crc32", Crc32.GdEw, 0, Sse4_2) },
        { Crc32GdEd, new("crc32", Crc32.GdEd, 0, Sse4_2) },
        { Crc32GqEq, new("crc32", Crc32.GqEq, 0, Sse4_2) },

        // CVTDQ2PD
        { Cvtdq2pdVxWx, new("cvtdq2pd", Cvtdq2pd.VxWx, 0, Sse2) },
        { Vcvtdq2pdVxWxV128, new("vcvtdq2pd", Cvtdq2pd.VxWxV128, 0, Avx) },
        { Vcvtdq2pdVyWxV256, new("vcvtdq2pd", Cvtdq2pd.VyWxV256, 0, Avx) },
        { Vcvtdq2pdVxWxE128, new("vcvtdq2pd", Cvtdq2pd.VxWxE128, 0, Avx512_VL) },
        { Vcvtdq2pdVyWxE256, new("vcvtdq2pd", Cvtdq2pd.VyWxE256, 0, Avx512_VL) },
        { Vcvtdq2pdVzWyE512, new("vcvtdq2pd", Cvtdq2pd.VzWyE512, 0, Avx512_F) },

        // CVTDQ2PS
        { Cvtdq2psVxWx, new("cvtdq2ps", Cvtdq2ps.VxWx, 0, Sse2) },
        { Vcvtdq2psVxWxV128, new("vcvtdq2ps", Cvtdq2ps.VxWxV128, 0, Avx) },
        { Vcvtdq2psVyWyV256, new("vcvtdq2ps", Cvtdq2ps.VyWyV256, 0, Avx) },
        { Vcvtdq2psVxWxE128, new("vcvtdq2ps", Cvtdq2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtdq2psVyWyE256, new("vcvtdq2ps", Cvtdq2ps.VyWyE256, 0, Avx512_VL) },
        { Vcvtdq2psVzWzE512, new("vcvtdq2ps", Cvtdq2ps.VzWzE512, 0, Avx512_F) },

        // CVTNE2PS2BF16
        { Vcvtne2ps2bf16VxHxWxE128, new("vcvtne2ps2bf16", Cvtne2ps2bf16.VxHxWxE128, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtne2ps2bf16VyHyWyE256, new("vcvtne2ps2bf16", Cvtne2ps2bf16.VyHyWyE256, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtne2ps2bf16VzHzWzE512, new("vcvtne2ps2bf16", Cvtne2ps2bf16.VzHzWzE512, 0, Avx512_F, Avx512_BF16) },

        // CVTNEPS2BF16
        { Vcvtneps2bf16VxWxE128, new("vcvtneps2bf16", Cvtneps2bf16.VxWxE128, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtneps2bf16VyWyE256, new("vcvtneps2bf16", Cvtneps2bf16.VyWyE256, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtneps2bf16VzWzE512, new("vcvtneps2bf16", Cvtneps2bf16.VzWzE512, 0, Avx512_F, Avx512_BF16) },

        // CVTPD2DQ
        { Cvtpd2dqVxWx, new("cvtpd2dq", Cvtpd2dq.VxWx, 0, Sse2) },
        { Vcvtpd2dqVxWxV128, new("vcvtpd2dq", Cvtpd2dq.VxWxV128, 0, Avx) },
        { Vcvtpd2dqVxWyV256, new("vcvtpd2dq", Cvtpd2dq.VxWyV256, 0, Avx) },
        { Vcvtpd2dqVxWxE128, new("vcvtpd2dq", Cvtpd2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvtpd2dqVxWyE256, new("vcvtpd2dq", Cvtpd2dq.VxWyE256, 0, Avx512_VL) },
        { Vcvtpd2dqVyWzE512, new("vcvtpd2dq", Cvtpd2dq.VyWzE512, 0, Avx512_F) },

        // CVTPD2PI
        { Cvtpd2piPqWx, new("cvtpd2pi", Cvtpd2pi.PqWx, 0, Mmx, Sse2) },

        // CVTPD2PS
        { Cvtpd2psVxWx, new("cvtpd2ps", Cvtpd2ps.VxWx, 0, Sse2) },
        { Vcvtpd2psVxWxV128, new("vcvtpd2ps", Cvtpd2ps.VxWxV128, 0, Avx) },
        { Vcvtpd2psVxWyV256, new("vcvtpd2ps", Cvtpd2ps.VxWyV256, 0, Avx) },
        { Vcvtpd2psVxWxE128, new("vcvtpd2ps", Cvtpd2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtpd2psVxWyE256, new("vcvtpd2ps", Cvtpd2ps.VxWyE256, 0, Avx512_VL) },
        { Vcvtpd2psVyWzE512, new("vcvtpd2ps", Cvtpd2ps.VyWzE512, 0, Avx512_F) },

        // CVTPD2QQ
        { Vcvtpd2qqVxWxE128, new("vcvtpd2qq", Cvtpd2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2qqVyWyE256, new("vcvtpd2qq", Cvtpd2qq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2qqVzWzE512, new("vcvtpd2qq", Cvtpd2qq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTPD2UDQ
        { Vcvtpd2udqVxWxE128, new("vcvtpd2udq", Cvtpd2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvtpd2udqVyWyE256, new("vcvtpd2udq", Cvtpd2udq.VyWyE256, 0, Avx512_VL) },
        { Vcvtpd2udqVzWzE512, new("vcvtpd2udq", Cvtpd2udq.VzWzE512, 0, Avx512_F) },

        // CVTPD2UQQ
        { Vcvtpd2uqqVxWxE128, new("vcvtpd2uqq", Cvtpd2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2uqqVyWyE256, new("vcvtpd2uqq", Cvtpd2uqq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2uqqVzWzE512, new("vcvtpd2uqq", Cvtpd2uqq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTPH2PS
        { Vcvtph2psVxWxV128, new("vcvtph2ps", Cvtph2ps.VxWxV128, 0, Avx, F16c) },
        { Vcvtph2psVyWxV256, new("vcvtph2ps", Cvtph2ps.VyWxV256, 0, Avx, F16c) },
        { Vcvtph2psVxWxE128, new("vcvtph2ps", Cvtph2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtph2psVyWxE256, new("vcvtph2ps", Cvtph2ps.VyWxE256, 0, Avx512_VL) },
        { Vcvtph2psVzWyE512, new("vcvtph2ps", Cvtph2ps.VzWyE512, 0, Avx512_F) },

        // CVTPI2PD
        { Cvtpi2pdVxQq, new("cvtpi2pd", Cvtpi2pd.VxQq, 0, Mmx, Sse) },

        // CVTPI2PS
        { Cvtpi2psVxQq, new("cvtpi2ps", Cvtpi2ps.VxQq, 0, Mmx, Sse) },

        // CVTPS2DQ
        { Cvtps2dqVxWx, new("cvtps2dq", Cvtps2dq.VxWx, 0, Sse2) },
        { Vcvtps2dqVxWxV128, new("vcvtps2dq", Cvtps2dq.VxWxV128, 0, Avx) },
        { Vcvtps2dqVyWyV256, new("vcvtps2dq", Cvtps2dq.VyWyV256, 0, Avx) },
        { Vcvtps2dqVxWxE128, new("vcvtps2dq", Cvtps2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvtps2dqVyWyE256, new("vcvtps2dq", Cvtps2dq.VyWyE256, 0, Avx512_VL) },
        { Vcvtps2dqVzWzE512, new("vcvtps2dq", Cvtps2dq.VzWzE512, 0, Avx512_F) },

        // CVTPS2PD
        { Cvtps2pdVxWx, new("cvtps2pd", Cvtps2pd.VxWx, 0, Sse2) },
        { Vcvtps2pdVxWxV128, new("vcvtps2pd", Cvtps2pd.VxWxV128, 0, Avx) },
        { Vcvtps2pdVyWxV256, new("vcvtps2pd", Cvtps2pd.VyWxV256, 0, Avx) },
        { Vcvtps2pdVxWxE128, new("vcvtps2pd", Cvtps2pd.VxWxE128, 0, Avx512_VL) },
        { Vcvtps2pdVyWxE256, new("vcvtps2pd", Cvtps2pd.VyWxE256, 0, Avx512_VL) },
        { Vcvtps2pdVzWyE512, new("vcvtps2pd", Cvtps2pd.VzWyE512, 0, Avx512_F) },

        // CVTPS2PH
        { Vcvtps2phWxVxIbV128, new("vcvtps2ph", Cvtps2ph.WxVxIbV128, 0, Avx, F16c) },
        { Vcvtps2phWxVyIbV256, new("vcvtps2ph", Cvtps2ph.WxVyIbV256, 0, Avx, F16c) },
        { Vcvtps2phWxVxIbE128, new("vcvtps2ph", Cvtps2ph.WxVxIbE128, 0, Avx512_VL) },
        { Vcvtps2phWxVyIbE256, new("vcvtps2ph", Cvtps2ph.WxVyIbE256, 0, Avx512_VL) },
        { Vcvtps2phWyVzIbE512, new("vcvtps2ph", Cvtps2ph.WyVzIbE512, 0, Avx512_F) },

        // CVTPS2PI
        { Cvtps2piPqWx, new("cvtps2pi", Cvtps2pi.PqWx, 0, Mmx, Sse) },

        // CVTPS2QQ
        { Vcvtps2qqVxWxE128, new("vcvtps2qq", Cvtps2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2qqVyWxE256, new("vcvtps2qq", Cvtps2qq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2qqVzWyE512, new("vcvtps2qq", Cvtps2qq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTPS2UDQ
        { Vcvtps2udqVxWxE128, new("vcvtps2udq", Cvtps2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvtps2udqVyWyE256, new("vcvtps2udq", Cvtps2udq.VyWyE256, 0, Avx512_VL) },
        { Vcvtps2udqVzWzE512, new("vcvtps2udq", Cvtps2udq.VzWzE512, 0, Avx512_F) },

        // CVTPS2UQQ
        { Vcvtps2uqqVxWxE128, new("vcvtps2uqq", Cvtps2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2uqqVyWxE256, new("vcvtps2uqq", Cvtps2uqq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2uqqVzWyE512, new("vcvtps2uqq", Cvtps2uqq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTQQ2PD
        { Vcvtqq2pdVxWxE128, new("vcvtqq2pd", Cvtqq2pd.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2pdVyWyE256, new("vcvtqq2pd", Cvtqq2pd.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2pdVzWzE512, new("vcvtqq2pd", Cvtqq2pd.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTQQ2PS
        { Vcvtqq2psVxWxE128, new("vcvtqq2ps", Cvtqq2ps.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2psVxWyE256, new("vcvtqq2ps", Cvtqq2ps.VxWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2psVyWzE512, new("vcvtqq2ps", Cvtqq2ps.VyWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTSD2SI
        { Cvtsd2siGdWx, new("cvtsd2si", Cvtsd2si.GdWx, 0, Sse2) },
        { Cvtsd2siGqWx, new("cvtsd2si", Cvtsd2si.GqWx, 0, Sse2) },
        { Vcvtsd2siGdWxV, new("vcvtsd2si", Cvtsd2si.GdWxV, 0, Avx) },
        { Vcvtsd2siGqWxV, new("vcvtsd2si", Cvtsd2si.GqWxV, 0, Avx) },
        { Vcvtsd2siGdWxE, new("vcvtsd2si", Cvtsd2si.GdWxE, 0, Avx512_F) },
        { Vcvtsd2siGqWxE, new("vcvtsd2si", Cvtsd2si.GqWxE, 0, Avx512_F) },

        // CVTSD2SS
        { Cvtsd2ssVxWx, new("cvtsd2ss", Cvtsd2ss.VxWx, 0, Sse2) },
        { Vcvtsd2ssVxHxWxV, new("vcvtsd2ss", Cvtsd2ss.VxHxWxV, 0, Avx) },
        { Vcvtsd2ssVxHxWxE, new("vcvtsd2ss", Cvtsd2ss.VxHxWxE, 0, Avx512_F) },

        // CVTSD2USI
        { Vcvtsd2usiGdWxE, new("vcvtsd2usi", Cvtsd2usi.GdWxE, 0, Avx512_F) },
        { Vcvtsd2usiGqWxE, new("vcvtsd2usi", Cvtsd2usi.GqWxE, 0, Avx512_F) },

        // CVTSD2SI
        { Cvtsi2sdVxEd, new("cvtsi2sd", Cvtsi2sd.VxEd, 0, Sse2) },
        { Cvtsi2sdVxEq, new("cvtsi2sd", Cvtsi2sd.VxEq, 0, Sse2) },
        { Vcvtsi2sdVxHxEdV, new("vcvtsi2sd", Cvtsi2sd.VxHxEdV, 0, Avx) },
        { Vcvtsi2sdVxHxEqV, new("vcvtsi2sd", Cvtsi2sd.VxHxEqV, 0, Avx) },
        { Vcvtsi2sdVxHxEdE, new("vcvtsi2sd", Cvtsi2sd.VxHxEdE, 0, Avx512_F) },
        { Vcvtsi2sdVxHxEqE, new("vcvtsi2sd", Cvtsi2sd.VxHxEqE, 0, Avx512_F) },

        // CVTSD2SI
        { Cvtsi2ssVxEd, new("cvtsi2ss", Cvtsi2ss.VxEd, 0, Sse) },
        { Cvtsi2ssVxEq, new("cvtsi2ss", Cvtsi2ss.VxEq, 0, Sse) },
        { Vcvtsi2ssVxHxEdV, new("vcvtsi2ss", Cvtsi2ss.VxHxEdV, 0, Avx) },
        { Vcvtsi2ssVxHxEqV, new("vcvtsi2ss", Cvtsi2ss.VxHxEqV, 0, Avx) },
        { Vcvtsi2ssVxHxEdE, new("vcvtsi2ss", Cvtsi2ss.VxHxEdE, 0, Avx512_F) },
        { Vcvtsi2ssVxHxEqE, new("vcvtsi2ss", Cvtsi2ss.VxHxEqE, 0, Avx512_F) },

        // CVTSS2SD
        { Cvtss2sdVxWx, new("cvtss2sd", Cvtss2sd.VxWx, 0, Sse2) },
        { Vcvtss2sdVxHxWxV, new("vcvtss2sd", Cvtss2sd.VxHxWxV, 0, Avx) },
        { Vcvtss2sdVxHxWxE, new("vcvtss2sd", Cvtss2sd.VxHxWxE, 0, Avx512_F) },

        // CVTSS2SI
        { Cvtss2siGdWx, new("cvtss2si", Cvtss2si.GdWx, 0, Sse) },
        { Cvtss2siGqWx, new("cvtss2si", Cvtss2si.GqWx, 0, Sse) },
        { Vcvtss2siGdWxV, new("vcvtss2si", Cvtss2si.GdWxV, 0, Avx) },
        { Vcvtss2siGqWxV, new("vcvtss2si", Cvtss2si.GqWxV, 0, Avx) },
        { Vcvtss2siGdWxE, new("vcvtss2si", Cvtss2si.GdWxE, 0, Avx512_F) },
        { Vcvtss2siGqWxE, new("vcvtss2si", Cvtss2si.GqWxE, 0, Avx512_F) },

        // CVTSS2USI
        { Vcvtss2usiGdWxE, new("vcvtss2usi", Cvtss2usi.GdWxE, 0, Avx512_F) },
        { Vcvtss2usiGqWxE, new("vcvtss2usi", Cvtss2usi.GqWxE, 0, Avx512_F) },

        // CVTTPD2DQ
        { Cvttpd2dqVxWx, new("cvttpd2dq", Cvttpd2dq.VxWx, 0, Sse2) },
        { Vcvttpd2dqVxWxV128, new("vcvttpd2dq", Cvttpd2dq.VxWxV128, 0, Avx) },
        { Vcvttpd2dqVxWyV256, new("vcvttpd2dq", Cvttpd2dq.VxWyV256, 0, Avx) },
        { Vcvttpd2dqVxWxE128, new("vcvttpd2dq", Cvttpd2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvttpd2dqVxWyE256, new("vcvttpd2dq", Cvttpd2dq.VxWyE256, 0, Avx512_VL) },
        { Vcvttpd2dqVyWzE512, new("vcvttpd2dq", Cvttpd2dq.VyWzE512, 0, Avx512_F) },

        // CVTTPD2PI
        { Cvttpd2piPqWx, new("cvttpd2pi", Cvttpd2pi.PqWx, 0, Mmx, Sse) },

        // CVTTPD2QQ
        { Vcvttpd2qqVxWxE128, new("vcvttpd2qq", Cvttpd2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2qqVyWyE256, new("vcvttpd2qq", Cvttpd2qq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2qqVzWzE512, new("vcvttpd2qq", Cvttpd2qq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTPD2UDQ
        { Vcvttpd2udqVxWxE128, new("vcvttpd2udq", Cvttpd2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvttpd2udqVxWyE256, new("vcvttpd2udq", Cvttpd2udq.VxWyE256, 0, Avx512_VL) },
        { Vcvttpd2udqVyWzE512, new("vcvttpd2udq", Cvttpd2udq.VyWzE512, 0, Avx512_F) },

        // CVTTPD2UQQ
        { Vcvttpd2uqqVxWxE128, new("vcvttpd2uqq", Cvttpd2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2uqqVyWyE256, new("vcvttpd2uqq", Cvttpd2uqq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2uqqVzWzE512, new("vcvttpd2uqq", Cvttpd2uqq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTPS2DQ
        { Cvttps2dqVxWx, new("cvttps2dq", Cvttps2dq.VxWx, 0, Sse2) },
        { Vcvttps2dqVxWxV128, new("vcvttps2dq", Cvttps2dq.VxWxV128, 0, Avx) },
        { Vcvttps2dqVyWyV256, new("vcvttps2dq", Cvttps2dq.VyWyV256, 0, Avx) },
        { Vcvttps2dqVxWxE128, new("vcvttps2dq", Cvttps2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvttps2dqVyWyE256, new("vcvttps2dq", Cvttps2dq.VyWyE256, 0, Avx512_VL) },
        { Vcvttps2dqVzWzE512, new("vcvttps2dq", Cvttps2dq.VzWzE512, 0, Avx512_F) },

        // CVTTPS2PI
        { Cvttps2piPqWx, new("cvttps2pi", Cvttps2pi.PqWx, 0, Mmx, Sse) },

        // CVTTPS2QQ
        { Vcvttps2qqVxWxE128, new("vcvttps2qq", Cvtps2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2qqVyWxE256, new("vcvttps2qq", Cvtps2qq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2qqVzWyE512, new("vcvttps2qq", Cvtps2qq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTPS2UDQ
        { Vcvttps2udqVxWxE128, new("vcvttps2udq", Cvttps2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvttps2udqVyWyE256, new("vcvttps2udq", Cvttps2udq.VyWyE256, 0, Avx512_VL) },
        { Vcvttps2udqVzWzE512, new("vcvttps2udq", Cvttps2udq.VzWzE512, 0, Avx512_F) },

        // CVTTPS2UQQ
        { Vcvttps2uqqVxWxE128, new("vcvttps2uqq", Cvttps2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2uqqVyWxE256, new("vcvttps2uqq", Cvttps2uqq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2uqqVzWyE512, new("vcvttps2uqq", Cvttps2uqq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTSD2SI
        { Cvttsd2siGdWx, new("cvttsd2si", Cvttsd2si.GdWx, 0, Sse2) },
        { Cvttsd2siGqWx, new("cvttsd2si", Cvttsd2si.GqWx, 0, Sse2) },
        { Vcvttsd2siGdWxV, new("vcvttsd2si", Cvttsd2si.GdWxV, 0, Avx) },
        { Vcvttsd2siGqWxV, new("vcvttsd2si", Cvttsd2si.GqWxV, 0, Avx) },
        { Vcvttsd2siGdWxE, new("vcvttsd2si", Cvttsd2si.GdWxE, 0, Avx512_F) },
        { Vcvttsd2siGqWxE, new("vcvttsd2si", Cvttsd2si.GqWxE, 0, Avx512_F) },

        // CVTTSD2USI
        { Vcvttsd2usiGdWxE, new("vcvttsd2usi", Cvttsd2usi.GdWxE, 0, Avx512_F) },
        { Vcvttsd2usiGqWxE, new("vcvttsd2usi", Cvttsd2usi.GqWxE, 0, Avx512_F) },

        // CVTTSS2SI
        { Cvttss2siGdWx, new("cvttss2si", Cvttss2si.GdWx, 0, Sse) },
        { Cvttss2siGqWx, new("cvttss2si", Cvttss2si.GqWx, 0, Sse) },
        { Vcvttss2siGdWxV, new("vcvttss2si", Cvttss2si.GdWxV, 0, Avx) },
        { Vcvttss2siGqWxV, new("vcvttss2si", Cvttss2si.GqWxV, 0, Avx) },
        { Vcvttss2siGdWxE, new("vcvttss2si", Cvttss2si.GdWxE, 0, Avx512_F) },
        { Vcvttss2siGqWxE, new("vcvttss2si", Cvttss2si.GqWxE, 0, Avx512_F) },

        // CVTTSS2USI
        { Vcvttss2usiGdWxE, new("vcvttss2usi", Cvttss2usi.GdWxE, 0, Avx512_F) },
        { Vcvttss2usiGqWxE, new("vcvttss2usi", Cvttss2usi.GqWxE, 0, Avx512_F) },

        // CVTUDQ2PD
        { Vcvtudq2pdVxWxE128, new("vcvtudq2pd", Cvtudq2pd.VxWxE128, 0, Avx512_VL) },
        { Vcvtudq2pdVyWxE256, new("vcvtudq2pd", Cvtudq2pd.VyWxE256, 0, Avx512_VL) },
        { Vcvtudq2pdVzWyE512, new("vcvtudq2pd", Cvtudq2pd.VzWyE512, 0, Avx512_F) },

        // CVTUDQ2PS
        { Vcvtudq2psVxWxE128, new("vcvtudq2ps", Cvtudq2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtudq2psVyWyE256, new("vcvtudq2ps", Cvtudq2ps.VyWyE256, 0, Avx512_VL) },
        { Vcvtudq2psVzWzE512, new("vcvtudq2ps", Cvtudq2ps.VzWzE512, 0, Avx512_F) },

        // CVTUQQ2PD
        { Vcvtuqq2pdVxWxE128, new("vcvtuqq2pd", Cvtuqq2pd.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2pdVyWyE256, new("vcvtuqq2pd", Cvtuqq2pd.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2pdVzWzE512, new("vcvtuqq2pd", Cvtuqq2pd.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTUQQ2PS
        { Vcvtuqq2psVxWxE128, new("vcvtuqq2ps", Cvtuqq2ps.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2psVxWyE256, new("vcvtuqq2ps", Cvtuqq2ps.VxWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2psVyWzE512, new("vcvtuqq2ps", Cvtuqq2ps.VyWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTUSI2SD
        { Vcvtusi2sdVxHxEdE, new("vcvtusi2sd", Cvtusi2sd.VxHxEdE, 0, Avx512_F) },
        { Vcvtusi2sdVxHxEqE, new("vcvtusi2sd", Cvtusi2sd.VxHxEqE, 0, Avx512_F) },

        // CVTUSI2SS
        { Vcvtusi2ssVxHxEdE, new("vcvtusi2ss", Cvtusi2ss.VxHxEdE, 0, Avx512_F) },
        { Vcvtusi2ssVxHxEqE, new("vcvtusi2ss", Cvtusi2ss.VxHxEqE, 0, Avx512_F) },

        // CWD / CDQ / CQO
        { Opcode.Cwd, new("cwd", Instruction.Cwd._, 0) },
        { Opcode.Cdq, new("cdq", Instruction.Cdq._, 0) },
        { Opcode.Cqo, new("cqo", Instruction.Cqo._, 0) },
        #endregion

        #region D.. Opcodes
        // DAA
        { Opcode.Daa, new("daa", Instruction.Daa._, 0) },

        // DAS
        { Opcode.Das, new("das", Instruction.Das._, 0) },

        // DBPSADBW
        { VdbpsadbwVxHxWxIbE128, new("vdbpsadbw", Dbpsadbw.VxHxWxIbE128, 0, Avx512_VL, Avx512_BW) },
        { VdbpsadbwVyHyWyIbE256, new("vdbpsadbw", Dbpsadbw.VyHyWyIbE256, 0, Avx512_VL, Avx512_BW) },
        { VdbpsadbwVzHzWzIbE512, new("vdbpsadbw", Dbpsadbw.VzHzWzIbE512, 0, Avx512_F, Avx512_BW) },

        // DEC
        { DecEb, new("dec", Dec.Eb, Lockable) },
        { DecEw, new("dec", Dec.Ew, Lockable) },
        { DecEd, new("dec", Dec.Ed, Lockable) },
        { DecEq, new("dec", Dec.Eq, Lockable) },
        { DecZw, new("dec", Dec.Zw, 0) },
        { DecZd, new("dec", Dec.Zd, 0) },

        // DIV
        { DivEb, new("div", Div.Eb, 0) },
        { DivEw, new("div", Div.Ew, 0) },
        { DivEd, new("div", Div.Ed, 0) },
        { DivEq, new("div", Div.Eq, 0) },

        // DIVPD
        { DivpdVxWx, new("divpd", Divpd.VxWx, 0, Sse2) },
        { VdivpdVxHxWxV128, new("vdivpd", Divpd.VxHxWxV128, 0, Avx) },
        { VdivpdVyHyWyV256, new("vdivpd", Divpd.VyHyWyV256, 0, Avx) },
        { VdivpdVxHxWxE128, new("vdivpd", Divpd.VxHxWxE128, 0, Avx512_VL) },
        { VdivpdVyHyWyE256, new("vdivpd", Divpd.VyHyWyE256, 0, Avx512_VL) },
        { VdivpdVzHzWzE512, new("vdivpd", Divpd.VzHzWzE512, 0, Avx512_F) },

        // DIVPS
        { DivpsVxWx, new("divps", Divps.VxWx, 0, Sse) },
        { VdivpsVxHxWxV128, new("vdivps", Divps.VxHxWxV128, 0, Avx) },
        { VdivpsVyHyWyV256, new("vdivps", Divps.VyHyWyV256, 0, Avx) },
        { VdivpsVxHxWxE128, new("vdivps", Divps.VxHxWxE128, 0, Avx512_VL) },
        { VdivpsVyHyWyE256, new("vdivps", Divps.VyHyWyE256, 0, Avx512_VL) },
        { VdivpsVzHzWzE512, new("vdivps", Divps.VzHzWzE512, 0, Avx512_F) },

        // DIVSD
        { DivsdVxWx, new("divsd", Divsd.VxWx, 0, Sse2) },
        { VdivsdVxHxWxV, new("vdivsd", Divsd.VxHxWxV, 0, Avx) },
        { VdivsdVxHxWxE, new("vdivsd", Divsd.VxHxWxE, 0, Avx512_F) },

        // DIVSS
        { DivssVxWx, new("divss", Divss.VxWx, 0, Sse) },
        { VdivssVxHxWxV, new("vdivss", Divss.VxHxWxV, 0, Avx) },
        { VdivssVxHxWxE, new("vdivss", Divss.VxHxWxE, 0, Avx512_F) },

        // DPBF16PS
        { Vdpbf16psVxHxWxE128, new("vdpbf16ps", Dpbf16ps.VxHxWxE128, 0, Avx512_VL, Avx512_BF16) },
        { Vdpbf16psVyHyWyE256, new("vdpbf16ps", Dpbf16ps.VyHyWyE256, 0, Avx512_VL, Avx512_BF16) },
        { Vdpbf16psVzHzWzE512, new("vdpbf16ps", Dpbf16ps.VzHzWzE512, 0, Avx512_F, Avx512_BF16) },

        // DPPD
        { DppdVxWxIb, new("dppd", Dppd.VxWxIb, 0, Sse4_1) },
        { VdppdVxHxWxIbV128, new("vdppd", Dppd.VxHxWxIbV128, 0, Avx) },

        // DPPS
        { DppsVxWxIb, new("dpps", Dpps.VxWxIb, 0, Sse4_1) },
        { VdppsVxHxWxIbV128, new("vdpps", Dpps.VxHxWxIbV128, 0, Avx) },
        { VdppsVyHyWyIbV256, new("vdpps", Dpps.VyHyWyIbV256, 0, Avx) },
        #endregion
    });
}
