/* =============================================================================
 * File:   OpcodeDetail.List.cs
 * Author: Cole Tobin
 * =============================================================================
 * Purpose:
 *
 * Lists all the opcodes supported by Sharp86. `GetList()` is generated by
 *   Sharp86.Generator in the repository root.
 * =============================================================================
 * Copyright (c) 2021 Cole Tobin
 *
 * This file is part of Sharp86.
 *
 * Sharp86 is free software: you can redistribute it and/or modify it under the
 *   terms of the GNU General Public License as published by the Free Software
 *   Foundation, either version 3 of the License, or (at your option) any later
 *   version.
 *
 * Sharp86 is distributed in the hope that it will be useful, but WITHOUT ANY
 *   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 *   details.
 *
 * You should have received a copy of the GNU General Public License along with
 *   Sharp86. If not, see <http://www.gnu.org/licenses/>.
 * =============================================================================
 */
using static Sharp86.Cpu.Decoder.Opcode;
using static Sharp86.Cpu.Decoder.OpcodeDetailAttributes;
using Sharp86.Cpu.Instruction;
using static Sharp86.Cpu.IsaExtension;
using System.Collections.ObjectModel;

namespace Sharp86.Cpu.Decoder;
public partial class OpcodeDetail
{
    /// <summary>
    /// A mapping of an <cref>Opcode</cref> to an <cref>OpcodeDetail</cref> object
    /// </summary>
    public static readonly ReadOnlyDictionary<Opcode, OpcodeDetail> List = new(new Dictionary<Opcode, OpcodeDetail>(4096)
    {
        // ABOVE: there's currently about 3700 opcodes; round up to 4096

        { Opcode.Error, new("error", Instruction.Error._, 0) },

        #region 4.. Opcodes
        // 4FMADDPS
        { V4fmaddpsVzHzMxE512, new("v4fmaddps", _4fmaddps.VzHzMxE512, 0, Avx512_4FMAPS) },

        // 4FMADDSS
        { V4fmaddssVzHzMxE, new("v4fmaddss", _4fnmaddss.VzHzMxE, 0, Avx512_4FMAPS) },

        // 4FNMADDPS
        { V4fnmaddpsVzHzMxE512, new("v4fnmaddps", _4fnmaddps.VzHzMxE512, 0, Avx512_4FMAPS) },

        // 4FNMADDSS
        { V4fnmaddssVzHzMxE, new("v4fnmaddss", _4fnmaddss.VzHzMxE, 0, Avx512_4FMAPS) },
        #endregion

        #region A.. Opcodes
        // AAA
        { Opcode.Aaa, new("aaa", Instruction.Aaa._, 0) },

        // AAD
        { AadIb, new("aad", Aad.Ib, 0) },

        // AAM
        { AamIb, new("aam", Aam.Ib, 0) },

        // AAS
        { Opcode.Aas, new("aas", Instruction.Aas._, 0) },

        // ADC
        { AdcALIb, new("adc", Adc.ALIb, 0) }, // acc, imm
        { AdcAXIw, new("adc", Adc.AXIw, 0) },
        { AdcEAXId, new("adc", Adc.EAXId, 0) },
        { AdcRAXId, new("adc", Adc.RAXId, 0) },
        { AdcEbIb, new("adc", Adc.EbIb, Lockable) }, // r/m, imm
        { AdcEwIw, new("adc", Adc.EwIw, Lockable) },
        { AdcEdId, new("adc", Adc.EdId, Lockable) },
        { AdcEqId, new("adc", Adc.EqId, Lockable) },
        { AdcEwIb, new("adc", Adc.EwIb, Lockable) }, // r/m, imm8
        { AdcEdIb, new("adc", Adc.EdIb, Lockable) },
        { AdcEqIb, new("adc", Adc.EqIb, Lockable) },
        { AdcEbGb, new("adc", Adc.EbGb, Lockable) }, // r/m, reg
        { AdcEwGw, new("adc", Adc.EwGw, Lockable) },
        { AdcEdGd, new("adc", Adc.EdGd, Lockable) },
        { AdcEqGq, new("adc", Adc.EqGq, Lockable) },
        { AdcGbEb, new("adc", Adc.GbEb, 0) }, // reg, r/m
        { AdcGwEw, new("adc", Adc.GwEw, 0) },
        { AdcGdEd, new("adc", Adc.GdEd, 0) },
        { AdcGqEq, new("adc", Adc.GqEq, 0) },

        // ADCX
        { AdcxGdEd, new("adcx", Adcx.GdEd, 0, Adx) },
        { AdcxGqEq, new("adcx", Adcx.GqEq, 0, Adx) },

        // ADD
        { AddALIb, new("add", Add.ALIb, 0) }, // acc, imm
        { AddAXIw, new("add", Add.AXIw, 0) },
        { AddEAXId, new("add", Add.EAXId, 0) },
        { AddRAXId, new("add", Add.RAXId, 0) },
        { AddEbIb, new("add", Add.EbIb, Lockable) }, // r/m, imm
        { AddEwIw, new("add", Add.EwIw, Lockable) },
        { AddEdId, new("add", Add.EdId, Lockable) },
        { AddEqId, new("add", Add.EqId, Lockable) },
        { AddEwIb, new("add", Add.EwIb, Lockable) }, // r/m, imm8
        { AddEdIb, new("add", Add.EdIb, Lockable) },
        { AddEqIb, new("add", Add.EqIb, Lockable) },
        { AddEbGb, new("add", Add.EbGb, Lockable) }, // r/m, reg
        { AddEwGw, new("add", Add.EwGw, Lockable) },
        { AddEdGd, new("add", Add.EdGd, Lockable) },
        { AddEqGq, new("add", Add.EqGq, Lockable) },
        { AddGbEb, new("add", Add.GbEb, 0) }, // reg, r/m
        { AddGwEw, new("add", Add.GwEw, 0) },
        { AddGdEd, new("add", Add.GdEd, 0) },
        { AddGqEq, new("add", Add.GqEq, 0) },

        // ADDPD
        { AddpdVxWx, new("addpd", Addpd.VxWx, 0, Sse2) },
        { VaddpdVxHxWxV128, new("vaddpd", Addpd.VxHxWxV128, 0, Avx) },
        { VaddpdVyHyWyV256, new("vaddpd", Addpd.VyHyWyV256, 0, Avx) },
        { VaddpdVxHxWxE128, new("vaddpd", Addpd.VxHxWxE128, 0, Avx512_VL) },
        { VaddpdVyHyWyE256, new("vaddpd", Addpd.VyHyWyE256, 0, Avx512_VL) },
        { VaddpdVzHzWzE512, new("vaddpd", Addpd.VzHzWzE512, 0, Avx512_F) },

        // ADDPS
        { AddpsVxWx, new("addpd", Addps.VxWx, 0, Sse) },
        { VaddpsVxHxWxV128, new("vaddps", Addps.VxHxWxV128, 0, Avx) },
        { VaddpsVyHyWyV256, new("vaddps", Addps.VyHyWyV256, 0, Avx) },
        { VaddpsVxHxWxE128, new("vaddps", Addps.VxHxWxE128, 0, Avx512_VL) },
        { VaddpsVyHyWyE256, new("vaddps", Addps.VyHyWyE256, 0, Avx512_VL) },
        { VaddpsVzHzWzE512, new("vaddps", Addps.VzHzWzE512, 0, Avx512_F) },

        // ADDSD
        { AddsdVxWx, new("addsd", Addsd.VxWx, 0, Sse2) },
        { VaddsdVxHxWxV, new("vaddsd", Addsd.VxHxWxV, 0, Avx) },
        { VaddsdVxHxWxE, new("vaddsd", Addsd.VxHxWxE, 0, Avx512_F) },

        // ADDSD
        { AddssVxWx, new("addss", Addss.VxWx, 0, Sse) },
        { VaddssVxHxWxV, new("vaddss", Addss.VxHxWxV, 0, Avx) },
        { VaddssVxHxWxE, new("vaddss", Addss.VxHxWxE, 0, Avx512_F) },

        // ADDSUBPD
        { AddsubpdVxWx, new("addsubpd", Addsubpd.VxWx, 0, Sse3) },
        { VaddsubpdVxHxWxV128, new("vaddsubpd", Addsubpd.VxHxWxV128, 0, Avx) },
        { VaddsubpdVyHyWyV256, new("vaddsubpd", Addsubpd.VyHyWyV256, 0, Avx) },

        // ADOX
        { AdoxGdEd, new("adox", Adox.GdEd, 0, Adx) },
        { AdoxGqEq, new("adox", Adox.GqEq, 0, Adx) },

        // AESDEC
        { AesdecVxWx, new("aesdec", Aesdec.VxWx, 0, AesNI) },
        { VaesdecVxHxWxV128, new("vaesdec", Aesdec.VxHxWxV128, 0, Avx, AesNI) },
        { VaesdecVyHyWyV256, new("vaesdec", Aesdec.VyHyWyV256, 0, Avx, Vaes) },
        { VaesdecVxHxWxE128, new("vaesdec", Aesdec.VxHxWxE128, 0, Avx512_VL, AesNI) },
        { VaesdecVyHyWyE256, new("vaesdec", Aesdec.VyHyWyE256, 0, Avx512_VL, AesNI) },
        { VaesdecVzHzWzE512, new("vaesdec", Aesdec.VzHzWzE512, 0, Avx512_F, AesNI) },

        // AESDEC128KL
        // TODO: Prepare attribute?
        { Aesdec128klVxM, new("aesdec128kl", Aesdec128kl.VxM, 0, AesKle) },

        // AESDEC256KL
        // TODO: Prepare attribute?
        { Aesdec256klVxMz, new("aesdec256kl", Aesdec256kl.VxMz, 0, AesKle) },

        // AESDECLAST
        { AesdeclastVxWx, new("aesdeclast", Aesdeclast.VxWx, 0, AesNI) },
        { VaesdeclastVxHxWxV128, new("vaesdeclast", Aesdeclast.VxHxWxV128, 0, Avx, AesNI) },
        { VaesdeclastVyHyWyV256, new("vaesdeclast", Aesdeclast.VyHyWyV256, 0, Avx, Vaes) },
        { VaesdeclastVxHxWxE128, new("vaesdeclast", Aesdeclast.VxHxWxE128, 0, Avx512_VL, AesNI) },
        { VaesdeclastVyHyWyE256, new("vaesdeclast", Aesdeclast.VyHyWyE256, 0, Avx512_VL, AesNI) },
        { VaesdeclastVzHzWzE512, new("vaesdeclast", Aesdeclast.VzHzWzE512, 0, Avx512_F, AesNI) },

        // AESDECWIDE128KL
        // TODO: Prepare attribute?
        { Aesdecwide128klM, new("Aesdecwide128kl", Aesdecwide128kl.M, 0, AesKle) },

        // AESDECWIDE256KL
        // TODO: Prepare attribute?
        { Aesdecwide256klMz, new("aesdecwide256kl", Aesdecwide256kl.Mz, 0, AesKle) },

        // AESENC
        { AesencVxWx, new("aesenc", Aesenc.VxWx, 0, AesNI) },
        { VaesencVxHxWxV128, new("vaesenc", Aesenc.VxHxWxV128, 0, Avx, AesNI) },
        { VaesencVyHyWyV256, new("vaesenc", Aesenc.VyHyWyV256, 0, Avx, Vaes) },
        { VaesencVxHxWxE128, new("vaesenc", Aesenc.VxHxWxE128, 0, Avx512_VL, Vaes) },
        { VaesencVyHyWyE256, new("vaesenc", Aesenc.VyHyWyE256, 0, Avx512_VL, Vaes) },
        { VaesencVzHzWzE512, new("vaesenc", Aesenc.VzHzWzE512, 0, Avx512_F, Vaes) },

        // AESENC128KL
        // TOOD: Prepare attribute?
        { Aesenc128klVxM, new("aesenc128kl", Aesenc128kl.VxM, 0, AesKle) },

        // AESENC256KL
        // TOOD: Prepare attribute?
        { Aesenc256klVxMz, new("aesenc256kl", Aesenc256kl.VxMz, 0, AesKle) },

        // AESENCLAST
        { AesenclastVxWx, new("aesenclast", Aesenclast.VxWx, 0, AesNI) },
        { VaesenclastVxHxWxV128, new("vaesenclast", Aesenclast.VxHxWxV128, 0, Avx, AesNI) },
        { VaesenclastVyHyWyV256, new("vaesenclast", Aesenclast.VyHyWyV256, 0, Avx, Vaes) },
        { VaesenclastVxHxWxE128, new("vaesenclast", Aesenclast.VxHxWxE128, 0, Avx512_VL, Vaes) },
        { VaesenclastVyHyWyE256, new("vaesenclast", Aesenclast.VyHyWyE256, 0, Avx512_VL, Vaes) },
        { VaesenclastVzHzWzE512, new("vaesenclast", Aesenclast.VzHzWzE512, 0, Avx512_F, Vaes) },

        // AESENCWIDE128KL
        // TODO: Prepare attribute?
        { Aesencwide128klM, new("aesencwide128kl", Aesencwide128kl.M, 0, AesKle) },

        // AESENCWIDE256KL
        // TODO: Prepare attribute?
        { Aesencwide256klMz, new("aesencwide256kl", Aesencwide256kl.Mz, 0, AesKle) },

        // AESIMC
        { AesimcVxWx, new("aesimc", Aesimc.VxWx, 0, AesNI) },
        { VaesimcVxWxV128, new("vaesimc", Aesimc.VxWxV128, 0, Avx) },

        // AESKEYGENASSIST
        { AeskeygenassistVxWxIb, new("aeskeygenassist", Aeskeygenassist.VxWxIb, 0, AesNI) },
        { VaeskeygenassistVxWxIbV128, new("vaeskeygenassist", Aeskeygenassist.VxWxIbV128, 0, Avx) },

        // AND
        { AndALIb, new("and", And.ALIb, 0) }, // acc, imm
        { AndAXIw, new("and", And.AXIw, 0) },
        { AndEAXId, new("and", And.EAXId, 0) },
        { AndRAXId, new("and", And.RAXId, 0) },
        { AndEbIb, new("and", And.EbIb, Lockable) }, // r/m, imm
        { AndEwIw, new("and", And.EwIw, Lockable) },
        { AndEdId, new("and", And.EdId, Lockable) },
        { AndEqId, new("and", And.EqId, Lockable) },
        { AndEwIb, new("and", And.EwIb, Lockable) }, // r/m, imm8
        { AndEdIb, new("and", And.EdIb, Lockable) },
        { AndEqIb, new("and", And.EqIb, Lockable) },
        { AndEbGb, new("and", And.EbGb, Lockable) }, // r/m, reg
        { AndEwGw, new("and", And.EwGw, Lockable) },
        { AndEdGd, new("and", And.EdGd, Lockable) },
        { AndEqGq, new("and", And.EqGq, Lockable) },
        { AndGbEb, new("and", And.GbEb, 0) }, // reg, r/m
        { AndGwEw, new("and", And.GwEw, 0) },
        { AndGdEd, new("and", And.GdEd, 0) },
        { AndGqEq, new("and", And.GqEq, 0) },

        // ANDN
        { AndnGdBdEd, new("andn", Andn.GdBdEd, 0, Bmi1) },
        { AndnGqBqEq, new("andn", Andn.GqBqEq, 0, Bmi1) },

        // ALIGND
        { ValigndVxHxWxIbE128, new("valignd", Alignd.VxHxWxIbE128, 0, Avx512_VL) },
        { ValigndVyHyWyIbE256, new("valignd", Alignd.VyHyWyIbE256, 0, Avx512_VL) },
        { ValigndVzHzWzIbE512, new("valignd", Alignd.VzHzWzIbE512, 0, Avx512_F) },

        // ALIGNQ
        { ValignqVxHxWxIbE128, new("valignq", Alignq.VxHxWxIbE128, 0, Avx512_VL) },
        { ValignqVyHyWyIbE256, new("valignq", Alignq.VyHyWyIbE256, 0, Avx512_VL) },
        { ValignqVzHzWzIbE512, new("valignq", Alignq.VzHzWzIbE512, 0, Avx512_F) },

        // ANDPD
        { AndpdVxWx, new("andpd", Andpd.VxWx, 0, Sse2) },
        { VandpdVxHxWxV128, new("vandpd", Andpd.VxHxWxV128, 0, Avx) },
        { VandpdVyHyWyV256, new("vandpd", Andpd.VyHyWyV256, 0, Avx) },
        { VandpdVxHxWxE128, new("vandpd", Andpd.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandpdVyHyWyE256, new("vandpd", Andpd.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandpdVzHzWzE512, new("vandpd", Andpd.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ANDPS
        { AndpsVxWx, new("andps", Andps.VxWx, 0, Sse) },
        { VandpsVxHxWxV128, new("vandps", Andps.VxHxWxV128, 0, Avx) },
        { VandpsVyHyWyV256, new("vandps", Andps.VyHyWyV256, 0, Avx) },
        { VandpsVxHxWxE128, new("vandps", Andps.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandpsVyHyWyE256, new("vandps", Andps.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandpsVzHzWzE512, new("vandps", Andps.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ANDNPD
        { AndnpdVxWx, new("andnpd", Andnpd.VxWx, 0, Sse2) },
        { VandnpdVxHxWxV128, new("vandnpd", Andnpd.VxHxWxV128, 0, Avx) },
        { VandnpdVyHyWyV256, new("vandnpd", Andnpd.VyHyWyV256, 0, Avx) },
        { VandnpdVxHxWxE128, new("vandnpd", Andnpd.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandnpdVyHyWyE256, new("vandnpd", Andnpd.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandnpdVzHzWzE512, new("vandnpd", Andnpd.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ANDNPS
        { AndnpsVxWx, new("andnps", Andnps.VxWx, 0, Sse) },
        { VandnpsVxHxWxV128, new("vandnps", Andnps.VxHxWxV128, 0, Avx) },
        { VandnpsVyHyWyV256, new("vandnps", Andnps.VyHyWyV256, 0, Avx) },
        { VandnpsVxHxWxE128, new("vandnps", Andnps.VxHxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { VandnpsVyHyWyE256, new("vandnps", Andnps.VyHyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { VandnpsVzHzWzE512, new("vandnps", Andnps.VzHzWzE512, 0, Avx512_F, Avx512_DQ) },

        // ARPL
        { ArplEwGw, new("arpl", Arpl.EwGw, 0) },
        #endregion

        #region B.. Opcodes
        // BEXTR
        { BextrGdEdBd, new("bextr", Bextr.GdEdBd, 0, Bmi1) },
        { BextrGqEqBq, new("bextr", Bextr.GqEqBq, 0, Bmi1) },

        // BLENDMPD
        { VblendmpdVxHxWxE128, new("vblendmpd", Blendmpd.VxHxWxE128, 0, Avx512_VL) },
        { VblendmpdVyHyWyE256, new("vblendmpd", Blendmpd.VyHyWyE256, 0, Avx512_VL) },
        { VblendmpdVzHzWzE512, new("vblendmpd", Blendmpd.VzHzWzE512, 0, Avx512_F) },

        // BLENDMPS
        { VblendmpsVxHxWxE128, new("vblendmps", Blendmps.VxHxWxE128, 0, Avx512_VL) },
        { VblendmpsVyHyWyE256, new("vblendmps", Blendmps.VyHyWyE256, 0, Avx512_VL) },
        { VblendmpsVzHzWzE512, new("vblendmps", Blendmps.VzHzWzE512, 0, Avx512_F) },

        // BLENDPD
        { BlendpdVxWxIb, new("blendpd", Blendpd.VxWxIb, 0, Sse4_1) },
        { VblendpdVxHxWxIbV128, new("vblendpd", Blendpd.VxHxWxIbV128, 0, Avx) },
        { VblendpdVyHyWyIbV256, new("vblendpd", Blendpd.VyHyWyIbV256, 0, Avx) },

        // BLENDPS
        { BlendpsVxWxIb, new("blendps", Blendps.VxWxIb, 0, Sse4_1) },
        { VblendpsVxHxWxIbV128, new("vblendps", Blendps.VxHxWxIbV128, 0, Avx) },
        { VblendpsVyHyWyIbV256, new("vblendps", Blendps.VyHyWyIbV256, 0, Avx) },

        // BLENDVPD
        { BlendvpdVxWx, new("blendvpd", Blendvpd.VxWx, 0, Sse4_1) },
        { VblendvpdVxHxWxLxV128, new("vblendvpd", Blendvpd.VxHxWxLxV128, 0, Avx) },
        { VblendvpdVyHyWyLyV256, new("vblendvpd", Blendvpd.VyHyWyLyV256, 0, Avx) },

        // BLENDVPS
        { BlendvpsVxWx, new("blendvps", Blendvps.VxWx, 0, Sse4_1) },
        { VblendvpsVxHxWxLxV128, new("vblendvps", Blendvps.VxHxWxLxV128, 0, Avx) },
        { VblendvpsVyHyWyLyV256, new("vblendvps", Blendvps.VyHyWyLyV256, 0, Avx) },

        // BLSI
        { BlsiBdEd, new("blsi", Blsi.BdEd, 0, Bmi1) },
        { BlsiBqEq, new("blsi", Blsi.BqEq, 0, Bmi1) },

        // BLSMSK
        { BlsmskBdEd, new("blsmsk", Blsmsk.BdEd, 0, Bmi1) },
        { BlsmskBqEq, new("blsmsk", Blsmsk.BqEq, 0, Bmi1) },

        // BLSR
        { BlsrBdEd, new("blsr", Blsr.BdEd, 0, Bmi1) },
        { BlsrBqEq, new("blsr", Blsr.BqEq, 0, Bmi1) },

        // BNDCL
        { BndclBGxEd, new("bndcl", Bndcl.BGxEd, 0, Mpx) },
        { BndclBGxEq, new("bndcl", Bndcl.BGxEq, 0, Mpx) },

        // BNDCU
        { BndcuBGxEd, new("bndcu", Bndcu.BGxEd, 0, Mpx) },
        { BndcuBGxEq, new("bndcu", Bndcu.BGxEq, 0, Mpx) },

        // BNDCN
        { BndcnBGxEd, new("bndcn", Bndcn.BGxEd, 0, Mpx) },
        { BndcnBGxEq, new("bndcn", Bndcn.BGxEq, 0, Mpx) },

        // BNDLDX
        { BndldxBGxM, new("bndldx", Bndldx.BGxM, 0, Mpx) },

        // BNDMK
        { BndmkBGxMd, new("bndmk", Bndmk.BGxMd, 0, Mpx) },
        { BndmkBGxMq, new("bndmk", Bndmk.BGxMq, 0, Mpx) },

        // BNDMOV
        { BndmovBGxBEq, new("bndmov", Bndmov.BGxBEq, 0, Mpx) },
        { BndmovBGxBEx, new("bndmov", Bndmov.BGxBEx, 0, Mpx) },
        { BndmovBEqBGx, new("bndmov", Bndmov.BEqBGx, 0, Mpx) },
        { BndmovBExBGx, new("bndmov", Bndmov.BExBGx, 0, Mpx) },

        // BNDSTX
        { BndstxMBGx, new("bndstx", Bndstx.MBGx, 0, Mpx) },

        // BOUND
        { BoundGwMd, new("bound", Bound.GwMd, 0) },
        { BoundGdMq, new("bound", Bound.GdMq, 0) },

        // BROADCASTx (VEX)
        { Vbroadcastf128VyMxV256, new("vbroadcastf128", Broadcastf128.VyMxV256, 0, Avx) }, // ..F128
        { VbroadcastsdVyMqV256, new("vbroadcastsd", Broadcastsd.VyMqV256, 0, Avx) }, // ..SD
        { VbroadcastsdVyUxV256, new("vbroadcastsd", Broadcastsd.VyUxV256, 0, Avx2) },
        { VbroadcastssVxMdV128, new("vbroadcastss", Broadcastss.VxMdV128, 0, Avx) }, // ..SS
        { VbroadcastssVyMdV256, new("vbroadcastss", Broadcastss.VyMdV256, 0, Avx) },
        { VbroadcastssVxUxV128, new("vbroadcastss", Broadcastss.VxUxV128, 0, Avx2) },
        { VbroadcastssVyUxV256, new("vbroadcastss", Broadcastss.VyUxV256, 0, Avx2) },
        // BROADCASTx (EVEX)
        { Vbroadcastf32x2VyWxE256, new("vbroadcastf32x2", Broadcastf32x2.VyWxE256, 0, Avx512_VL, Avx512_DQ) }, // ..F32X2
        { Vbroadcastf32x2VzWxE512, new("vbroadcastf32x2", Broadcastf32x2.VzWxE512, 0, Avx512_F, Avx512_DQ) },
        { Vbroadcastf32x4VyMxE256, new("vbroadcastf32x4", Broadcastf32x4.VyMxE256, 0, Avx512_VL) }, // ..F32X4
        { Vbroadcastf32x4VzMxE512, new("vbroadcastf32x4", Broadcastf32x4.VzMxE512, 0, Avx512_F) },
        { Vbroadcastf32x8VzMyE512, new("vbroadcastf32x8", Broadcastf32x8.VzMyE512, 0, Avx512_F, Avx512_DQ) }, // ..F32X8
        { Vbroadcastf64x2VyMxE256, new("vbroadcastf64x2", Broadcastf64x2.VyMxE256, 0, Avx512_VL, Avx512_DQ) }, // ..F64X2
        { Vbroadcastf64x2VzMxE512, new("vbroadcastf64x2", Broadcastf64x2.VzMxE512, 0, Avx512_F, Avx512_DQ) },
        { Vbroadcastf64x4VzMyE512, new("vbroadcastf64x4", Broadcastf64x4.VzMyE512, 0, Avx512_F) }, // ..F64X4
        { VbroadcastsdVyWxE256, new("vbroadcastsd", Broadcastsd.VyWxE256, 0, Avx512_VL) }, // ..SD
        { VbroadcastsdVzWxE512, new("vbroadcastsd", Broadcastsd.VzWxE512, 0, Avx512_F) },
        { VbroadcastssVxWxE128, new("vbroadcastss", Broadcastss.VxWxE128, 0, Avx512_VL) }, // ..SS
        { VbroadcastssVyWxE256, new("vbroadcastss", Broadcastss.VyWxE256, 0, Avx512_VL) },
        { VbroadcastssVzWxE512, new("vbroadcastss", Broadcastss.VzWxE512, 0, Avx512_F) },

        // BSF
        { BsfGwEw, new("bsf", Bsf.GwEw, 0) },
        { BsfGdEd, new("bsf", Bsf.GdEd, 0) },
        { BsfGqEq, new("bsf", Bsf.GqEq, 0) },

        // BSR
        { BsrGwEw, new("bsr", Bsr.GwEw, 0) },
        { BsrGdEd, new("bsr", Bsr.GdEd, 0) },
        { BsrGqEq, new("bsr", Bsr.GqEq, 0) },

        // BSWAP
        { BswapZw, new("bswap", Bswap.Zw, 0) },
        { BswapZd, new("bswap", Bswap.Zd, 0) },
        { BswapZq, new("bswap", Bswap.Zq, 0) },

        // BT
        { BtEwGw, new("bt", Bt.EwGw, 0) },
        { BtEdGd, new("bt", Bt.EdGd, 0) },
        { BtEqGq, new("bt", Bt.EqGq, 0) },
        { BtEwIb, new("bt", Bt.EwIb, 0) },
        { BtEdIb, new("bt", Bt.EdIb, 0) },
        { BtEqIb, new("bt", Bt.EqIb, 0) },

        // BTC
        { BtcEwGw, new("btc", Btc.EwGw, 0) },
        { BtcEdGd, new("btc", Btc.EdGd, 0) },
        { BtcEqGq, new("btc", Btc.EqGq, 0) },
        { BtcEwIb, new("btc", Btc.EwIb, 0) },
        { BtcEdIb, new("btc", Btc.EdIb, 0) },
        { BtcEqIb, new("btc", Btc.EqIb, 0) },

        // BTR
        { BtrEwGw, new("btr", Btr.EwGw, 0) },
        { BtrEdGd, new("btr", Btr.EdGd, 0) },
        { BtrEqGq, new("btr", Btr.EqGq, 0) },
        { BtrEwIb, new("btr", Btr.EwIb, 0) },
        { BtrEdIb, new("btr", Btr.EdIb, 0) },
        { BtrEqIb, new("btr", Btr.EqIb, 0) },

        // BTS
        { BtsEwGw, new("bts", Bts.EwGw, 0) },
        { BtsEdGd, new("bts", Bts.EdGd, 0) },
        { BtsEqGq, new("bts", Bts.EqGq, 0) },
        { BtsEwIb, new("bts", Bts.EwIb, 0) },
        { BtsEdIb, new("bts", Bts.EdIb, 0) },
        { BtsEqIb, new("bts", Bts.EqIb, 0) },

        // BZHI
        { BzhiGdEdBd, new("bzhi", Bzhi.GdEdBd, 0, Bmi2) },
        { BzhiGqEqBq, new("bzhi", Bzhi.GqEqBq, 0, Bmi2) },
        #endregion

        #region C.. Opcodes
        // CALL
        { CallJw, new("call", Call.Jw, 0) },
        { CallJd, new("call", Call.Jd, 0) },
        { CallEw, new("call", Call.Ew, 0) },
        { CallEd, new("call", Call.Ed, 0) },
        { CallEq, new("call", Call.Eq, 0) },
        // CALLF
        { CallApww, new("callf", Call.Apww, 0) },
        { CallApwd, new("callf", Call.Apwd, 0) },
        { CallMpww, new("callf", Call.Mpww, 0) },
        { CallMpwd, new("callf", Call.Mpwd, 0) },
        { CallMpwq, new("callf", Call.Mpwq, 0) },

        // CBW / CWDE / CDQE
        { Opcode.Cbw, new("cbw", Instruction.Cbw._, 0) },
        { Opcode.Cwde, new("cwde", Instruction.Cwde._, 0) },
        { Opcode.Cdqe, new("cdqe", Instruction.Cdqe._, 0) },

        // CLAC
        { Opcode.Clac, new("clac", Instruction.Clac._, 0, Smap) },

        // CLC
        { Opcode.Clc, new("clc", Instruction.Clc._, 0) },

        // CLD
        { Opcode.Cld, new("cld", Instruction.Cld._, 0) },

        // CLDEMOTE
        { CldemoteMb, new("cldemote", Instruction.Cldemote.Mb, 0, IsaExtension.Cldemote) },

        // CLFLUSH
        { ClflushMb, new("clflush", Clflush.Mb, 0, Clfsh) },

        // CLFLUSHOPT
        { ClflushoptMb, new("clflushopt", Instruction.Clflushopt.Mb, 0, IsaExtension.Clflushopt) },

        // CLI
        { Opcode.Cli, new("cli", Instruction.Cli._, 0) },

        // CLRSSBSY
        { ClrssbsyMq, new("clrssbsy", Clrssbsy.Mq, 0, CetSS) },

        // CLTS
        { Opcode.Clts, new("clts", Instruction.Clts._, 0) },

        // CLUI
        { Opcode.Clui, new("clui", Instruction.Clui._, 0, Uintr) },

        // CLWB
        { ClwbMb, new("clwb", Instruction.Clwb.Mb, 0, IsaExtension.Clwb) },

        // CMC
        { Opcode.Cmc, new("cmc", Instruction.Cmc._, 0) },

        // CMOVcc
        { CmovccGwEw, new("cmovCC", Cmovcc.GwEw, 0) },
        { CmovccGdEd, new("cmovCC", Cmovcc.GdEd, 0) },
        { CmovccGqEq, new("cmovCC", Cmovcc.GqEq, 0) },

        // CMP
        { CmpALIb, new("cmp", Cmp.ALIb, 0) }, // acc, imm
        { CmpAXIw, new("cmp", Cmp.AXIw, 0) },
        { CmpEAXId, new("cmp", Cmp.EAXId, 0) },
        { CmpRAXId, new("cmp", Cmp.RAXId, 0) },
        { CmpEbIb, new("cmp", Cmp.EbIb, 0) }, // r/m, imm
        { CmpEwIw, new("cmp", Cmp.EwIw, 0) },
        { CmpEdId, new("cmp", Cmp.EdId, 0) },
        { CmpEqId, new("cmp", Cmp.EqId, 0) },
        { CmpEwIb, new("cmp", Cmp.EwIb, 0) }, // r/m, imm8
        { CmpEdIb, new("cmp", Cmp.EdIb, 0) },
        { CmpEqIb, new("cmp", Cmp.EqIb, 0) },
        { CmpEbGb, new("cmp", Cmp.EbGb, 0) }, // r/m, reg
        { CmpEwGw, new("cmp", Cmp.EwGw, 0) },
        { CmpEdGd, new("cmp", Cmp.EdGd, 0) },
        { CmpEqGq, new("cmp", Cmp.EqGq, 0) },
        { CmpGbEb, new("cmp", Cmp.GbEb, 0) }, // reg, r/m
        { CmpGwEw, new("cmp", Cmp.GwEw, 0) },
        { CmpGdEd, new("cmp", Cmp.GdEd, 0) },
        { CmpGqEq, new("cmp", Cmp.GqEq, 0) },

        // CMPPD
        { CmppdVxWxIb, new("cmppd", Cmppd.VxWxIb, 0, Sse2) },
        { VcmppdVxHxWxIbV128, new("vcmppd", Cmppd.VxHxWxIbV128, 0, Avx) },
        { VcmppdVyHyWyIbV256, new("vcmppd", Cmppd.VyHyWyIbV256, 0, Avx) },
        { VcmppdKGqHxWxIbE128, new("vcmppd", Cmppd.KGqHxWxIbE128, 0, Avx512_VL) },
        { VcmppdKGqHyWyIbE256, new("vcmppd", Cmppd.KGqHyWyIbE256, 0, Avx512_VL) },
        { VcmppdKGqHzWzIbE512, new("vcmppd", Cmppd.KGqHzWzIbE512, 0, Avx512_F) },

        // CMPPS
        { CmppsVxWxIb, new("cmpps", Cmpps.VxWxIb, 0, Sse) },
        { VcmppsVxHxWxIbV128, new("vcmpps", Cmpps.VxHxWxIbV128, 0, Avx) },
        { VcmppsVyHyWyIbV256, new("vcmpps", Cmpps.VyHyWyIbV256, 0, Avx) },
        { VcmppsKGqHxWxIbE128, new("vcmpps", Cmpps.KGqHxWxIbE128, 0, Avx512_VL) },
        { VcmppsKGqHyWyIbE256, new("vcmpps", Cmpps.KGqHyWyIbE256, 0, Avx512_VL) },
        { VcmppsKGqHzWzIbE512, new("vcmpps", Cmpps.KGqHzWzIbE512, 0, Avx512_F) },

        // CMPS
        { Opcode.Cmpsb, new("cmpsb", Instruction.Cmpsb._, 0) },
        { Opcode.Cmpsw, new("cmpsw", Instruction.Cmpsw._, 0) },
        { Opcode.Cmpsd, new("cmpsd", Instruction.Cmpsd._, 0) },
        { Opcode.Cmpsq, new("cmpsq", Instruction.Cmpsq._, 0) },

        // CMPSD
        { CmpsdVxWxIb, new("cmpsd", Instruction.Cmpsd.VxWxIb, 0, Sse2) },
        { VcmpsdVxHxWxIbV, new("vcmpsd", Instruction.Cmpsd.VxHxWxIbV, 0, Avx) },
        { VcmpsdKGqHxWxIbE, new("vcmpsd", Instruction.Cmpsd.KGqHxWxIbE, 0, Avx512_F) },

        // CMPSS
        { CmpssVxWxIb, new("cmpss", Cmpss.VxWxIb, 0, Sse) },
        { VcmpssVxHxWxIbV, new("vcmpss", Cmpss.VxHxWxIbV, 0, Avx) },
        { VcmpssKGqHxWxIbE, new("vcmpss", Cmpss.KGqHxWxIbE, 0, Avx512_F) },

        // CMPXCHG
        { CmpxchgEbGb, new("cmpxchg", Cmpxchg.EbGb, 0) },
        { CmpxchgEwGw, new("cmpxchg", Cmpxchg.EwGw, 0) },
        { CmpxchgEdGd, new("cmpxchg", Cmpxchg.EdGd, 0) },
        { CmpxchgEqGq, new("cmpxchg", Cmpxchg.EqGq, 0) },

        // CMPXCHG8B / CMPXCHG16B
        { Cmpxchg8bMq, new("cmpxchg8b", Cmpxchg8b.Mq, 0) },
        { Cmpxchg16bMx, new("cmpxchg16b", Instruction.Cmpxchg16b.Mx, 0, IsaExtension.Cmpxchg16b) },

        // COMISD
        { ComisdVxWx, new("comisd", Comisd.VxWx, 0, Sse2) },
        { VcomisdVxWxV, new("vcomisd", Comisd.VxWxV, 0, Avx) },
        { VcomisdVxWxE, new("vcomisd", Comisd.VxWxE, 0, Avx512_F) },

        // COMISS
        { ComissVxWx, new("comiss", Comiss.VxWx, 0, Sse) },
        { VcomissVxWxV, new("vcomiss", Comiss.VxWxV, 0, Avx) },
        { VcomissVxWxE, new("vcomiss", Comiss.VxWxE, 0, Avx512_F) },

        // COMPRESSPD
        { VcompresspdWxVxE128, new("vcompresspd", Compresspd.WxVxE128, 0, Avx512_VL) },
        { VcompresspdWyVyE256, new("vcompresspd", Compresspd.WyVyE256, 0, Avx512_VL) },
        { VcompresspdWzVzE512, new("vcompresspd", Compresspd.WzVzE512, 0, Avx512_F) },

        // COMPRESSPS
        { VcompresspsWxVxE128, new("vcompressps", Compressps.WxVxE128, 0, Avx512_VL) },
        { VcompresspsWyVyE256, new("vcompressps", Compressps.WyVyE256, 0, Avx512_VL) },
        { VcompresspsWzVzE512, new("vcompressps", Compressps.WzVzE512, 0, Avx512_F) },

        // CPUID
        { Opcode.Cpuid, new("cpuid", Instruction.Cpuid._, 0) },

        // CRC32
        { Crc32GdEb, new("crc32", Crc32.GdEb, 0, Sse4_2) },
        { Crc32GqEb, new("crc32", Crc32.GqEb, 0, Sse4_2) },
        { Crc32GdEw, new("crc32", Crc32.GdEw, 0, Sse4_2) },
        { Crc32GdEd, new("crc32", Crc32.GdEd, 0, Sse4_2) },
        { Crc32GqEq, new("crc32", Crc32.GqEq, 0, Sse4_2) },

        // CVTDQ2PD
        { Cvtdq2pdVxWx, new("cvtdq2pd", Cvtdq2pd.VxWx, 0, Sse2) },
        { Vcvtdq2pdVxWxV128, new("vcvtdq2pd", Cvtdq2pd.VxWxV128, 0, Avx) },
        { Vcvtdq2pdVyWxV256, new("vcvtdq2pd", Cvtdq2pd.VyWxV256, 0, Avx) },
        { Vcvtdq2pdVxWxE128, new("vcvtdq2pd", Cvtdq2pd.VxWxE128, 0, Avx512_VL) },
        { Vcvtdq2pdVyWxE256, new("vcvtdq2pd", Cvtdq2pd.VyWxE256, 0, Avx512_VL) },
        { Vcvtdq2pdVzWyE512, new("vcvtdq2pd", Cvtdq2pd.VzWyE512, 0, Avx512_F) },

        // CVTDQ2PS
        { Cvtdq2psVxWx, new("cvtdq2ps", Cvtdq2ps.VxWx, 0, Sse2) },
        { Vcvtdq2psVxWxV128, new("vcvtdq2ps", Cvtdq2ps.VxWxV128, 0, Avx) },
        { Vcvtdq2psVyWyV256, new("vcvtdq2ps", Cvtdq2ps.VyWyV256, 0, Avx) },
        { Vcvtdq2psVxWxE128, new("vcvtdq2ps", Cvtdq2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtdq2psVyWyE256, new("vcvtdq2ps", Cvtdq2ps.VyWyE256, 0, Avx512_VL) },
        { Vcvtdq2psVzWzE512, new("vcvtdq2ps", Cvtdq2ps.VzWzE512, 0, Avx512_F) },

        // CVTNE2PS2BF16
        { Vcvtne2ps2bf16VxHxWxE128, new("vcvtne2ps2bf16", Cvtne2ps2bf16.VxHxWxE128, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtne2ps2bf16VyHyWyE256, new("vcvtne2ps2bf16", Cvtne2ps2bf16.VyHyWyE256, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtne2ps2bf16VzHzWzE512, new("vcvtne2ps2bf16", Cvtne2ps2bf16.VzHzWzE512, 0, Avx512_F, Avx512_BF16) },

        // CVTNEPS2BF16
        { Vcvtneps2bf16VxWxE128, new("vcvtneps2bf16", Cvtneps2bf16.VxWxE128, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtneps2bf16VyWyE256, new("vcvtneps2bf16", Cvtneps2bf16.VyWyE256, 0, Avx512_VL, Avx512_BF16) },
        { Vcvtneps2bf16VzWzE512, new("vcvtneps2bf16", Cvtneps2bf16.VzWzE512, 0, Avx512_F, Avx512_BF16) },

        // CVTPD2DQ
        { Cvtpd2dqVxWx, new("cvtpd2dq", Cvtpd2dq.VxWx, 0, Sse2) },
        { Vcvtpd2dqVxWxV128, new("vcvtpd2dq", Cvtpd2dq.VxWxV128, 0, Avx) },
        { Vcvtpd2dqVxWyV256, new("vcvtpd2dq", Cvtpd2dq.VxWyV256, 0, Avx) },
        { Vcvtpd2dqVxWxE128, new("vcvtpd2dq", Cvtpd2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvtpd2dqVxWyE256, new("vcvtpd2dq", Cvtpd2dq.VxWyE256, 0, Avx512_VL) },
        { Vcvtpd2dqVyWzE512, new("vcvtpd2dq", Cvtpd2dq.VyWzE512, 0, Avx512_F) },

        // CVTPD2PI
        { Cvtpd2piPqWx, new("cvtpd2pi", Cvtpd2pi.PqWx, 0, Mmx, Sse2) },

        // CVTPD2PS
        { Cvtpd2psVxWx, new("cvtpd2ps", Cvtpd2ps.VxWx, 0, Sse2) },
        { Vcvtpd2psVxWxV128, new("vcvtpd2ps", Cvtpd2ps.VxWxV128, 0, Avx) },
        { Vcvtpd2psVxWyV256, new("vcvtpd2ps", Cvtpd2ps.VxWyV256, 0, Avx) },
        { Vcvtpd2psVxWxE128, new("vcvtpd2ps", Cvtpd2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtpd2psVxWyE256, new("vcvtpd2ps", Cvtpd2ps.VxWyE256, 0, Avx512_VL) },
        { Vcvtpd2psVyWzE512, new("vcvtpd2ps", Cvtpd2ps.VyWzE512, 0, Avx512_F) },

        // CVTPD2QQ
        { Vcvtpd2qqVxWxE128, new("vcvtpd2qq", Cvtpd2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2qqVyWyE256, new("vcvtpd2qq", Cvtpd2qq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2qqVzWzE512, new("vcvtpd2qq", Cvtpd2qq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTPD2UDQ
        { Vcvtpd2udqVxWxE128, new("vcvtpd2udq", Cvtpd2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvtpd2udqVyWyE256, new("vcvtpd2udq", Cvtpd2udq.VyWyE256, 0, Avx512_VL) },
        { Vcvtpd2udqVzWzE512, new("vcvtpd2udq", Cvtpd2udq.VzWzE512, 0, Avx512_F) },

        // CVTPD2UQQ
        { Vcvtpd2uqqVxWxE128, new("vcvtpd2uqq", Cvtpd2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2uqqVyWyE256, new("vcvtpd2uqq", Cvtpd2uqq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtpd2uqqVzWzE512, new("vcvtpd2uqq", Cvtpd2uqq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTPH2PS
        { Vcvtph2psVxWxV128, new("vcvtph2ps", Cvtph2ps.VxWxV128, 0, Avx, F16c) },
        { Vcvtph2psVyWxV256, new("vcvtph2ps", Cvtph2ps.VyWxV256, 0, Avx, F16c) },
        { Vcvtph2psVxWxE128, new("vcvtph2ps", Cvtph2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtph2psVyWxE256, new("vcvtph2ps", Cvtph2ps.VyWxE256, 0, Avx512_VL) },
        { Vcvtph2psVzWyE512, new("vcvtph2ps", Cvtph2ps.VzWyE512, 0, Avx512_F) },

        // CVTPI2PD
        { Cvtpi2pdVxQq, new("cvtpi2pd", Cvtpi2pd.VxQq, 0, Mmx, Sse) },

        // CVTPI2PS
        { Cvtpi2psVxQq, new("cvtpi2ps", Cvtpi2ps.VxQq, 0, Mmx, Sse) },

        // CVTPS2DQ
        { Cvtps2dqVxWx, new("cvtps2dq", Cvtps2dq.VxWx, 0, Sse2) },
        { Vcvtps2dqVxWxV128, new("vcvtps2dq", Cvtps2dq.VxWxV128, 0, Avx) },
        { Vcvtps2dqVyWyV256, new("vcvtps2dq", Cvtps2dq.VyWyV256, 0, Avx) },
        { Vcvtps2dqVxWxE128, new("vcvtps2dq", Cvtps2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvtps2dqVyWyE256, new("vcvtps2dq", Cvtps2dq.VyWyE256, 0, Avx512_VL) },
        { Vcvtps2dqVzWzE512, new("vcvtps2dq", Cvtps2dq.VzWzE512, 0, Avx512_F) },

        // CVTPS2PD
        { Cvtps2pdVxWx, new("cvtps2pd", Cvtps2pd.VxWx, 0, Sse2) },
        { Vcvtps2pdVxWxV128, new("vcvtps2pd", Cvtps2pd.VxWxV128, 0, Avx) },
        { Vcvtps2pdVyWxV256, new("vcvtps2pd", Cvtps2pd.VyWxV256, 0, Avx) },
        { Vcvtps2pdVxWxE128, new("vcvtps2pd", Cvtps2pd.VxWxE128, 0, Avx512_VL) },
        { Vcvtps2pdVyWxE256, new("vcvtps2pd", Cvtps2pd.VyWxE256, 0, Avx512_VL) },
        { Vcvtps2pdVzWyE512, new("vcvtps2pd", Cvtps2pd.VzWyE512, 0, Avx512_F) },

        // CVTPS2PH
        { Vcvtps2phWxVxIbV128, new("vcvtps2ph", Cvtps2ph.WxVxIbV128, 0, Avx, F16c) },
        { Vcvtps2phWxVyIbV256, new("vcvtps2ph", Cvtps2ph.WxVyIbV256, 0, Avx, F16c) },
        { Vcvtps2phWxVxIbE128, new("vcvtps2ph", Cvtps2ph.WxVxIbE128, 0, Avx512_VL) },
        { Vcvtps2phWxVyIbE256, new("vcvtps2ph", Cvtps2ph.WxVyIbE256, 0, Avx512_VL) },
        { Vcvtps2phWyVzIbE512, new("vcvtps2ph", Cvtps2ph.WyVzIbE512, 0, Avx512_F) },

        // CVTPS2PI
        { Cvtps2piPqWx, new("cvtps2pi", Cvtps2pi.PqWx, 0, Mmx, Sse) },

        // CVTPS2QQ
        { Vcvtps2qqVxWxE128, new("vcvtps2qq", Cvtps2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2qqVyWxE256, new("vcvtps2qq", Cvtps2qq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2qqVzWyE512, new("vcvtps2qq", Cvtps2qq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTPS2UDQ
        { Vcvtps2udqVxWxE128, new("vcvtps2udq", Cvtps2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvtps2udqVyWyE256, new("vcvtps2udq", Cvtps2udq.VyWyE256, 0, Avx512_VL) },
        { Vcvtps2udqVzWzE512, new("vcvtps2udq", Cvtps2udq.VzWzE512, 0, Avx512_F) },

        // CVTPS2UQQ
        { Vcvtps2uqqVxWxE128, new("vcvtps2uqq", Cvtps2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2uqqVyWxE256, new("vcvtps2uqq", Cvtps2uqq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtps2uqqVzWyE512, new("vcvtps2uqq", Cvtps2uqq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTQQ2PD
        { Vcvtqq2pdVxWxE128, new("vcvtqq2pd", Cvtqq2pd.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2pdVyWyE256, new("vcvtqq2pd", Cvtqq2pd.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2pdVzWzE512, new("vcvtqq2pd", Cvtqq2pd.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTQQ2PS
        { Vcvtqq2psVxWxE128, new("vcvtqq2ps", Cvtqq2ps.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2psVxWyE256, new("vcvtqq2ps", Cvtqq2ps.VxWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtqq2psVyWzE512, new("vcvtqq2ps", Cvtqq2ps.VyWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTSD2SI
        { Cvtsd2siGdWx, new("cvtsd2si", Cvtsd2si.GdWx, 0, Sse2) },
        { Cvtsd2siGqWx, new("cvtsd2si", Cvtsd2si.GqWx, 0, Sse2) },
        { Vcvtsd2siGdWxV, new("vcvtsd2si", Cvtsd2si.GdWxV, 0, Avx) },
        { Vcvtsd2siGqWxV, new("vcvtsd2si", Cvtsd2si.GqWxV, 0, Avx) },
        { Vcvtsd2siGdWxE, new("vcvtsd2si", Cvtsd2si.GdWxE, 0, Avx512_F) },
        { Vcvtsd2siGqWxE, new("vcvtsd2si", Cvtsd2si.GqWxE, 0, Avx512_F) },

        // CVTSD2SS
        { Cvtsd2ssVxWx, new("cvtsd2ss", Cvtsd2ss.VxWx, 0, Sse2) },
        { Vcvtsd2ssVxHxWxV, new("vcvtsd2ss", Cvtsd2ss.VxHxWxV, 0, Avx) },
        { Vcvtsd2ssVxHxWxE, new("vcvtsd2ss", Cvtsd2ss.VxHxWxE, 0, Avx512_F) },

        // CVTSD2USI
        { Vcvtsd2usiGdWxE, new("vcvtsd2usi", Cvtsd2usi.GdWxE, 0, Avx512_F) },
        { Vcvtsd2usiGqWxE, new("vcvtsd2usi", Cvtsd2usi.GqWxE, 0, Avx512_F) },

        // CVTSD2SI
        { Cvtsi2sdVxEd, new("cvtsi2sd", Cvtsi2sd.VxEd, 0, Sse2) },
        { Cvtsi2sdVxEq, new("cvtsi2sd", Cvtsi2sd.VxEq, 0, Sse2) },
        { Vcvtsi2sdVxHxEdV, new("vcvtsi2sd", Cvtsi2sd.VxHxEdV, 0, Avx) },
        { Vcvtsi2sdVxHxEqV, new("vcvtsi2sd", Cvtsi2sd.VxHxEqV, 0, Avx) },
        { Vcvtsi2sdVxHxEdE, new("vcvtsi2sd", Cvtsi2sd.VxHxEdE, 0, Avx512_F) },
        { Vcvtsi2sdVxHxEqE, new("vcvtsi2sd", Cvtsi2sd.VxHxEqE, 0, Avx512_F) },

        // CVTSD2SI
        { Cvtsi2ssVxEd, new("cvtsi2ss", Cvtsi2ss.VxEd, 0, Sse) },
        { Cvtsi2ssVxEq, new("cvtsi2ss", Cvtsi2ss.VxEq, 0, Sse) },
        { Vcvtsi2ssVxHxEdV, new("vcvtsi2ss", Cvtsi2ss.VxHxEdV, 0, Avx) },
        { Vcvtsi2ssVxHxEqV, new("vcvtsi2ss", Cvtsi2ss.VxHxEqV, 0, Avx) },
        { Vcvtsi2ssVxHxEdE, new("vcvtsi2ss", Cvtsi2ss.VxHxEdE, 0, Avx512_F) },
        { Vcvtsi2ssVxHxEqE, new("vcvtsi2ss", Cvtsi2ss.VxHxEqE, 0, Avx512_F) },

        // CVTSS2SD
        { Cvtss2sdVxWx, new("cvtss2sd", Cvtss2sd.VxWx, 0, Sse2) },
        { Vcvtss2sdVxHxWxV, new("vcvtss2sd", Cvtss2sd.VxHxWxV, 0, Avx) },
        { Vcvtss2sdVxHxWxE, new("vcvtss2sd", Cvtss2sd.VxHxWxE, 0, Avx512_F) },

        // CVTSS2SI
        { Cvtss2siGdWx, new("cvtss2si", Cvtss2si.GdWx, 0, Sse) },
        { Cvtss2siGqWx, new("cvtss2si", Cvtss2si.GqWx, 0, Sse) },
        { Vcvtss2siGdWxV, new("vcvtss2si", Cvtss2si.GdWxV, 0, Avx) },
        { Vcvtss2siGqWxV, new("vcvtss2si", Cvtss2si.GqWxV, 0, Avx) },
        { Vcvtss2siGdWxE, new("vcvtss2si", Cvtss2si.GdWxE, 0, Avx512_F) },
        { Vcvtss2siGqWxE, new("vcvtss2si", Cvtss2si.GqWxE, 0, Avx512_F) },

        // CVTSS2USI
        { Vcvtss2usiGdWxE, new("vcvtss2usi", Cvtss2usi.GdWxE, 0, Avx512_F) },
        { Vcvtss2usiGqWxE, new("vcvtss2usi", Cvtss2usi.GqWxE, 0, Avx512_F) },

        // CVTTPD2DQ
        { Cvttpd2dqVxWx, new("cvttpd2dq", Cvttpd2dq.VxWx, 0, Sse2) },
        { Vcvttpd2dqVxWxV128, new("vcvttpd2dq", Cvttpd2dq.VxWxV128, 0, Avx) },
        { Vcvttpd2dqVxWyV256, new("vcvttpd2dq", Cvttpd2dq.VxWyV256, 0, Avx) },
        { Vcvttpd2dqVxWxE128, new("vcvttpd2dq", Cvttpd2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvttpd2dqVxWyE256, new("vcvttpd2dq", Cvttpd2dq.VxWyE256, 0, Avx512_VL) },
        { Vcvttpd2dqVyWzE512, new("vcvttpd2dq", Cvttpd2dq.VyWzE512, 0, Avx512_F) },

        // CVTTPD2PI
        { Cvttpd2piPqWx, new("cvttpd2pi", Cvttpd2pi.PqWx, 0, Mmx, Sse) },

        // CVTTPD2QQ
        { Vcvttpd2qqVxWxE128, new("vcvttpd2qq", Cvttpd2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2qqVyWyE256, new("vcvttpd2qq", Cvttpd2qq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2qqVzWzE512, new("vcvttpd2qq", Cvttpd2qq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTPD2UDQ
        { Vcvttpd2udqVxWxE128, new("vcvttpd2udq", Cvttpd2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvttpd2udqVxWyE256, new("vcvttpd2udq", Cvttpd2udq.VxWyE256, 0, Avx512_VL) },
        { Vcvttpd2udqVyWzE512, new("vcvttpd2udq", Cvttpd2udq.VyWzE512, 0, Avx512_F) },

        // CVTTPD2UQQ
        { Vcvttpd2uqqVxWxE128, new("vcvttpd2uqq", Cvttpd2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2uqqVyWyE256, new("vcvttpd2uqq", Cvttpd2uqq.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttpd2uqqVzWzE512, new("vcvttpd2uqq", Cvttpd2uqq.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTPS2DQ
        { Cvttps2dqVxWx, new("cvttps2dq", Cvttps2dq.VxWx, 0, Sse2) },
        { Vcvttps2dqVxWxV128, new("vcvttps2dq", Cvttps2dq.VxWxV128, 0, Avx) },
        { Vcvttps2dqVyWyV256, new("vcvttps2dq", Cvttps2dq.VyWyV256, 0, Avx) },
        { Vcvttps2dqVxWxE128, new("vcvttps2dq", Cvttps2dq.VxWxE128, 0, Avx512_VL) },
        { Vcvttps2dqVyWyE256, new("vcvttps2dq", Cvttps2dq.VyWyE256, 0, Avx512_VL) },
        { Vcvttps2dqVzWzE512, new("vcvttps2dq", Cvttps2dq.VzWzE512, 0, Avx512_F) },

        // CVTTPS2PI
        { Cvttps2piPqWx, new("cvttps2pi", Cvttps2pi.PqWx, 0, Mmx, Sse) },

        // CVTTPS2QQ
        { Vcvttps2qqVxWxE128, new("vcvttps2qq", Cvtps2qq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2qqVyWxE256, new("vcvttps2qq", Cvtps2qq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2qqVzWyE512, new("vcvttps2qq", Cvtps2qq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTPS2UDQ
        { Vcvttps2udqVxWxE128, new("vcvttps2udq", Cvttps2udq.VxWxE128, 0, Avx512_VL) },
        { Vcvttps2udqVyWyE256, new("vcvttps2udq", Cvttps2udq.VyWyE256, 0, Avx512_VL) },
        { Vcvttps2udqVzWzE512, new("vcvttps2udq", Cvttps2udq.VzWzE512, 0, Avx512_F) },

        // CVTTPS2UQQ
        { Vcvttps2uqqVxWxE128, new("vcvttps2uqq", Cvttps2uqq.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2uqqVyWxE256, new("vcvttps2uqq", Cvttps2uqq.VyWxE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvttps2uqqVzWyE512, new("vcvttps2uqq", Cvttps2uqq.VzWyE512, 0, Avx512_F, Avx512_DQ) },

        // CVTTSD2SI
        { Cvttsd2siGdWx, new("cvttsd2si", Cvttsd2si.GdWx, 0, Sse2) },
        { Cvttsd2siGqWx, new("cvttsd2si", Cvttsd2si.GqWx, 0, Sse2) },
        { Vcvttsd2siGdWxV, new("vcvttsd2si", Cvttsd2si.GdWxV, 0, Avx) },
        { Vcvttsd2siGqWxV, new("vcvttsd2si", Cvttsd2si.GqWxV, 0, Avx) },
        { Vcvttsd2siGdWxE, new("vcvttsd2si", Cvttsd2si.GdWxE, 0, Avx512_F) },
        { Vcvttsd2siGqWxE, new("vcvttsd2si", Cvttsd2si.GqWxE, 0, Avx512_F) },

        // CVTTSD2USI
        { Vcvttsd2usiGdWxE, new("vcvttsd2usi", Cvttsd2usi.GdWxE, 0, Avx512_F) },
        { Vcvttsd2usiGqWxE, new("vcvttsd2usi", Cvttsd2usi.GqWxE, 0, Avx512_F) },

        // CVTTSS2SI
        { Cvttss2siGdWx, new("cvttss2si", Cvttss2si.GdWx, 0, Sse) },
        { Cvttss2siGqWx, new("cvttss2si", Cvttss2si.GqWx, 0, Sse) },
        { Vcvttss2siGdWxV, new("vcvttss2si", Cvttss2si.GdWxV, 0, Avx) },
        { Vcvttss2siGqWxV, new("vcvttss2si", Cvttss2si.GqWxV, 0, Avx) },
        { Vcvttss2siGdWxE, new("vcvttss2si", Cvttss2si.GdWxE, 0, Avx512_F) },
        { Vcvttss2siGqWxE, new("vcvttss2si", Cvttss2si.GqWxE, 0, Avx512_F) },

        // CVTTSS2USI
        { Vcvttss2usiGdWxE, new("vcvttss2usi", Cvttss2usi.GdWxE, 0, Avx512_F) },
        { Vcvttss2usiGqWxE, new("vcvttss2usi", Cvttss2usi.GqWxE, 0, Avx512_F) },

        // CVTUDQ2PD
        { Vcvtudq2pdVxWxE128, new("vcvtudq2pd", Cvtudq2pd.VxWxE128, 0, Avx512_VL) },
        { Vcvtudq2pdVyWxE256, new("vcvtudq2pd", Cvtudq2pd.VyWxE256, 0, Avx512_VL) },
        { Vcvtudq2pdVzWyE512, new("vcvtudq2pd", Cvtudq2pd.VzWyE512, 0, Avx512_F) },

        // CVTUDQ2PS
        { Vcvtudq2psVxWxE128, new("vcvtudq2ps", Cvtudq2ps.VxWxE128, 0, Avx512_VL) },
        { Vcvtudq2psVyWyE256, new("vcvtudq2ps", Cvtudq2ps.VyWyE256, 0, Avx512_VL) },
        { Vcvtudq2psVzWzE512, new("vcvtudq2ps", Cvtudq2ps.VzWzE512, 0, Avx512_F) },

        // CVTUQQ2PD
        { Vcvtuqq2pdVxWxE128, new("vcvtuqq2pd", Cvtuqq2pd.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2pdVyWyE256, new("vcvtuqq2pd", Cvtuqq2pd.VyWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2pdVzWzE512, new("vcvtuqq2pd", Cvtuqq2pd.VzWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTUQQ2PS
        { Vcvtuqq2psVxWxE128, new("vcvtuqq2ps", Cvtuqq2ps.VxWxE128, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2psVxWyE256, new("vcvtuqq2ps", Cvtuqq2ps.VxWyE256, 0, Avx512_VL, Avx512_DQ) },
        { Vcvtuqq2psVyWzE512, new("vcvtuqq2ps", Cvtuqq2ps.VyWzE512, 0, Avx512_F, Avx512_DQ) },

        // CVTUSI2SD
        { Vcvtusi2sdVxHxEdE, new("vcvtusi2sd", Cvtusi2sd.VxHxEdE, 0, Avx512_F) },
        { Vcvtusi2sdVxHxEqE, new("vcvtusi2sd", Cvtusi2sd.VxHxEqE, 0, Avx512_F) },

        // CVTUSI2SS
        { Vcvtusi2ssVxHxEdE, new("vcvtusi2ss", Cvtusi2ss.VxHxEdE, 0, Avx512_F) },
        { Vcvtusi2ssVxHxEqE, new("vcvtusi2ss", Cvtusi2ss.VxHxEqE, 0, Avx512_F) },

        // CWD / CDQ / CQO
        { Opcode.Cwd, new("cwd", Instruction.Cwd._, 0) },
        { Opcode.Cdq, new("cdq", Instruction.Cdq._, 0) },
        { Opcode.Cqo, new("cqo", Instruction.Cqo._, 0) },
        #endregion

        #region D.. Opcodes
        // DAA
        { Opcode.Daa, new("daa", Instruction.Daa._, 0) },

        // DAS
        { Opcode.Das, new("das", Instruction.Das._, 0) },

        // DBPSADBW
        { VdbpsadbwVxHxWxIbE128, new("vdbpsadbw", Dbpsadbw.VxHxWxIbE128, 0, Avx512_VL, Avx512_BW) },
        { VdbpsadbwVyHyWyIbE256, new("vdbpsadbw", Dbpsadbw.VyHyWyIbE256, 0, Avx512_VL, Avx512_BW) },
        { VdbpsadbwVzHzWzIbE512, new("vdbpsadbw", Dbpsadbw.VzHzWzIbE512, 0, Avx512_F, Avx512_BW) },

        // DEC
        { DecEb, new("dec", Dec.Eb, Lockable) },
        { DecEw, new("dec", Dec.Ew, Lockable) },
        { DecEd, new("dec", Dec.Ed, Lockable) },
        { DecEq, new("dec", Dec.Eq, Lockable) },
        { DecZw, new("dec", Dec.Zw, 0) },
        { DecZd, new("dec", Dec.Zd, 0) },

        // DIV
        { DivEb, new("div", Div.Eb, 0) },
        { DivEw, new("div", Div.Ew, 0) },
        { DivEd, new("div", Div.Ed, 0) },
        { DivEq, new("div", Div.Eq, 0) },

        // DIVPD
        { DivpdVxWx, new("divpd", Divpd.VxWx, 0, Sse2) },
        { VdivpdVxHxWxV128, new("vdivpd", Divpd.VxHxWxV128, 0, Avx) },
        { VdivpdVyHyWyV256, new("vdivpd", Divpd.VyHyWyV256, 0, Avx) },
        { VdivpdVxHxWxE128, new("vdivpd", Divpd.VxHxWxE128, 0, Avx512_VL) },
        { VdivpdVyHyWyE256, new("vdivpd", Divpd.VyHyWyE256, 0, Avx512_VL) },
        { VdivpdVzHzWzE512, new("vdivpd", Divpd.VzHzWzE512, 0, Avx512_F) },

        // DIVPS
        { DivpsVxWx, new("divps", Divps.VxWx, 0, Sse) },
        { VdivpsVxHxWxV128, new("vdivps", Divps.VxHxWxV128, 0, Avx) },
        { VdivpsVyHyWyV256, new("vdivps", Divps.VyHyWyV256, 0, Avx) },
        { VdivpsVxHxWxE128, new("vdivps", Divps.VxHxWxE128, 0, Avx512_VL) },
        { VdivpsVyHyWyE256, new("vdivps", Divps.VyHyWyE256, 0, Avx512_VL) },
        { VdivpsVzHzWzE512, new("vdivps", Divps.VzHzWzE512, 0, Avx512_F) },

        // DIVSD
        { DivsdVxWx, new("divsd", Divsd.VxWx, 0, Sse2) },
        { VdivsdVxHxWxV, new("vdivsd", Divsd.VxHxWxV, 0, Avx) },
        { VdivsdVxHxWxE, new("vdivsd", Divsd.VxHxWxE, 0, Avx512_F) },

        // DIVSS
        { DivssVxWx, new("divss", Divss.VxWx, 0, Sse) },
        { VdivssVxHxWxV, new("vdivss", Divss.VxHxWxV, 0, Avx) },
        { VdivssVxHxWxE, new("vdivss", Divss.VxHxWxE, 0, Avx512_F) },

        // DPBF16PS
        { Vdpbf16psVxHxWxE128, new("vdpbf16ps", Dpbf16ps.VxHxWxE128, 0, Avx512_VL, Avx512_BF16) },
        { Vdpbf16psVyHyWyE256, new("vdpbf16ps", Dpbf16ps.VyHyWyE256, 0, Avx512_VL, Avx512_BF16) },
        { Vdpbf16psVzHzWzE512, new("vdpbf16ps", Dpbf16ps.VzHzWzE512, 0, Avx512_F, Avx512_BF16) },

        // DPPD
        { DppdVxWxIb, new("dppd", Dppd.VxWxIb, 0, Sse4_1) },
        { VdppdVxHxWxIbV128, new("vdppd", Dppd.VxHxWxIbV128, 0, Avx) },

        // DPPS
        { DppsVxWxIb, new("dpps", Dpps.VxWxIb, 0, Sse4_1) },
        { VdppsVxHxWxIbV128, new("vdpps", Dpps.VxHxWxIbV128, 0, Avx) },
        { VdppsVyHyWyIbV256, new("vdpps", Dpps.VyHyWyIbV256, 0, Avx) },
        #endregion

        #region E.. Opcodes
        // EMMS
        { Opcode.Emms, new("emms", Instruction.Emms._, 0, Mmx) },

        // ENCLS
        { Opcode.Encls, new("encls", Instruction.Encls._, 0, Sgx1) },

        // ENCLU
        { Opcode.Enclu, new("enclu", Instruction.Enclu._, 0, Sgx1) },

        // ENCLV
        { Opcode.Enclv, new("enclv", Instruction.Enclv._, 0, Oss) },

        // ENCODEKEY128
        { Encodekey128GdRd, new("encodekey128", Encodekey128.GdRd, 0, AesKle) },

        // ENCODEKEY256
        { Encodekey256GdRd, new("encodekey256", Encodekey256.GdRd, 0, AesKle) },

        // ENDBR32
        { Opcode.Endbr32, new("endbr32", Instruction.Endbr32._, 0, CetIbt) },

        // ENDBR64
        { Opcode.Endbr64, new("endbr64", Instruction.Endbr64._, 0, CetIbt) },

        // ENTER
        { EnterIwIbOp16, new("enter", Enter.IwIbOp16, 0) },
        { EnterIwIbOp32, new("enter", Enter.IwIbOp32, 0) },
        { EnterIwIbOp64, new("enter", Enter.IwIbOp64, 0) },

        // ENQCMD
        { EnqcmdGdMz, new("enqcmd", Instruction.Enqcmd.GdMz, 0, IsaExtension.Enqcmd) },
        { EnqcmdGqMz, new("enqcmd", Instruction.Enqcmd.GqMz, 0, IsaExtension.Enqcmd) },

        // EXPANDPD
        { VexpandpdVxWxE128, new("vexpandpd", Expandpd.VxWxE128, 0, Avx512_VL) },
        { VexpandpdVyWyE256, new("vexpandpd", Expandpd.VyWyE256, 0, Avx512_VL) },
        { VexpandpdVzWzE512, new("vexpandpd", Expandpd.VzWzE512, 0, Avx512_F) },

        // EXPANDPS
        { VexpandpsVxWxE128, new("vexpandps", Expandps.VxWxE128, 0, Avx512_VL) },
        { VexpandpsVyWyE256, new("vexpandps", Expandps.VyWyE256, 0, Avx512_VL) },
        { VexpandpsVzWzE512, new("vexpandps", Expandps.VzWzE512, 0, Avx512_F) },

        // VEXTRACTFx
        { Vextractf128WxVyIbV256, new("vextractf128", Extractf128.WxVyIbV256, 0, Avx) }, // ..128
        { Vextractf32x4WxVyIbE256, new("vextractf32x4", Extractf32x4.WxVyIbE256, 0, Avx512_VL) }, // ..32X4
        { Vextractf32x4WxVzIbE512, new("vextractf32x4", Extractf32x4.WxVzIbE512, 0, Avx512_F) },
        { Vextractf32x8WyVzIbE512, new("vextractf32x8", Extractf32x8.WyVzIbE512, 0, Avx512_F, Avx512_DQ) }, // 32X8
        { Vextractf64x2WxVyIbE256, new("vextractf64x2", Extractf64x2.WxVyIbE256, 0, Avx512_VL, Avx512_DQ) }, // 64X2
        { Vextractf64x2WxVzIbE512, new("vextractf64x2", Extractf64x2.WxVzIbE512, 0, Avx512_F, Avx512_DQ) },
        { Vextractf64x4WyVzIbE512, new("vextractf64x4", Extractf64x4.WyVzIbE512, 0, Avx512_F) }, // 64X4

        // VEXTRACTIx
        { Vextracti128WxVyIbV256, new("vextracti128", Extracti128.WxVyIbV256, 0, Avx2) }, // ..128
        { Vextracti32x4WxVyIbE256, new("vextracti32x4", Extracti32x4.WxVyIbE256, 0, Avx512_VL) }, // ..32X4
        { Vextracti32x4WxVzIbE512, new("vextracti32x4", Extracti32x4.WxVzIbE512, 0, Avx512_F) },
        { Vextracti32x8WyVzIbE512, new("vextracti32x8", Extracti32x8.WyVzIbE512, 0, Avx512_F, Avx512_DQ) }, // 32X8
        { Vextracti64x2WxVyIbE256, new("vextracti64x2", Extracti64x2.WxVyIbE256, 0, Avx512_VL, Avx512_DQ) }, // 64X2
        { Vextracti64x2WxVzIbE512, new("vextracti64x2", Extracti64x2.WxVzIbE512, 0, Avx512_F, Avx512_DQ) },
        { Vextracti64x4WyVzIbE512, new("vextracti64x4", Extracti64x4.WyVzIbE512, 0, Avx512_F) }, // 64X4

        // EXTRACTPS
        { ExtractpsEdVxIb, new("extractps", Extractps.EdVxIb, 0, Sse4_1) },
        { VextractpsEdVxIbV128, new("vextractps", Extractps.EdVxIbV128, 0, Avx) },
        { VextractpsEdVxIbE128, new("vextractps", Extractps.EdVxIbE128, 0, Avx512_F) },
        #endregion

        #region F.. Opcodes
        // F2XM1
        { Opcode.F2xm1, new("f2xm1", Instruction.F2xm1._, 0, IsaExtension.Fpu) },

        // FABS
        { Opcode.Fabs, new("fabs", Instruction.Fabs._, 0, IsaExtension.Fpu) },

        // FADD / FADDP / FIADD
        { FaddMd, new("fadd", Fadd.Md, 0, IsaExtension.Fpu) },
        { FaddMq, new("fadd", Fadd.Mq, 0, IsaExtension.Fpu) },
        { FaddST0STi, new("fadd", Fadd.ST0STi, 0, IsaExtension.Fpu) },
        { FaddSTiST0, new("fadd", Fadd.STiST0, 0, IsaExtension.Fpu) },
        { FaddpSTiST0, new("faddp", Faddp.STiST0, 0, IsaExtension.Fpu) },
        { FiaddMd, new("fiadd", Fiadd.Md, 0, IsaExtension.Fpu) },
        { FiaddMw, new("fiadd", Fiadd.Mw, 0, IsaExtension.Fpu) },

        // FBLD
        { FbldMt, new("fbld", Fbld.Mt, 0, IsaExtension.Fpu) },

        // FBSTP
        { FbstpMt, new("fbstp", Fbstp.Mt, 0, IsaExtension.Fpu) },

        // FCHS
        { Opcode.Fchs, new("fchs", Instruction.Fchs._, 0, IsaExtension.Fpu) },

        // FCLEX
        { Opcode.Fclex, new("fclex", Instruction.Fclex._, 0, IsaExtension.Fpu) },

        // FCMOVcc
        { FcmovccST0STi, new("fcmovcc", Fcmovcc.ST0STi, 0, IsaExtension.Fpu) },

        // FCOM / FCOMP / FCOMPP
        { FcomMd, new("fcom", Fcom.Md, 0, IsaExtension.Fpu) },
        { FcomMq, new("fcom", Fcom.Mq, 0, IsaExtension.Fpu) },
        { FcomSTi, new("fcom", Fcom.STi, 0, IsaExtension.Fpu) },
        { FcompMd, new("fcomp", Fcomp.Md, 0, IsaExtension.Fpu) },
        { FcompMq, new("fcomp", Fcomp.Mq, 0, IsaExtension.Fpu) },
        { FcompSTi, new("fcomp", Fcomp.STi, 0, IsaExtension.Fpu) },
        { Opcode.Fcompp, new("fcompp", Instruction.Fcompp._, 0, IsaExtension.Fpu) },

        // FCOMI / FCOMIP / FUCOMI / FUCOMIP
        { FcomiST0STi, new("fcomi", Fcomi.ST0STi, 0, IsaExtension.Fpu) },
        { FcomipST0STi, new("fcomip", Fcomip.ST0STi, 0, IsaExtension.Fpu) },
        { FucomiST0STi, new("fucomi", Fucomi.ST0STi, 0, IsaExtension.Fpu) },
        { FucomipST0STi, new("fucomip", Fucomip.ST0STi, 0, IsaExtension.Fpu) },

        // FCOS
        { Opcode.Fcos, new("fcos", Instruction.Fcos._, 0, IsaExtension.Fpu) },

        // FDECSTP
        { Opcode.Fdecstp, new("fdecstp", Instruction.Fdecstp._, 0, IsaExtension.Fpu) },

        // FDIV / FDIVP / FIDIV
        { FdivMd, new("fdiv", Fdiv.Md, 0, IsaExtension.Fpu) },
        { FdivMq, new("fdiv", Fdiv.Mq, 0, IsaExtension.Fpu) },
        { FdivST0STi, new("fdiv", Fdiv.ST0STi, 0, IsaExtension.Fpu) },
        { FdivSTiST0, new("fdiv", Fdiv.STiST0, 0, IsaExtension.Fpu) },
        { FdivpSTiST0, new("fdivp", Fdivp.STiST0, 0, IsaExtension.Fpu) },
        { FidivMd, new("fidiv", Fidiv.Md, 0, IsaExtension.Fpu) },
        { FidivMw, new("fidiv", Fidiv.Mw, 0, IsaExtension.Fpu) },

        // FDIVR / FDIVRP / FIDIVR
        { FdivrMd, new("fdivr", Fdivr.Md, 0, IsaExtension.Fpu) },
        { FdivrMq, new("fdivr", Fdivr.Mq, 0, IsaExtension.Fpu) },
        { FdivrST0STi, new("fdivr", Fdivr.ST0STi, 0, IsaExtension.Fpu) },
        { FdivrSTiST0, new("fdivr", Fdivr.STiST0, 0, IsaExtension.Fpu) },
        { FdivrpSTiST0, new("fdivrp", Fdivrp.STiST0, 0, IsaExtension.Fpu) },
        { FidivrMd, new("fidivr", Fidivr.Md, 0, IsaExtension.Fpu) },
        { FidivrMw, new("fidivr", Fidivr.Mw, 0, IsaExtension.Fpu) },

        // FEMMS
        { Opcode.Femms, new("femms", Instruction.Femms._, 0, _3DNow) },

        // FFREE
        { FfreeSTi, new("ffree", Ffree.STi, 0, IsaExtension.Fpu) },

        // FICOM / FICOMP
        { FicomMw, new("ficom", Ficom.Mw, 0, IsaExtension.Fpu) },
        { FicomMd, new("ficom", Ficom.Md, 0, IsaExtension.Fpu) },
        { FicompMw, new("ficomp", Ficomp.Mw, 0, IsaExtension.Fpu) },
        { FicompMd, new("ficomp", Ficomp.Md, 0, IsaExtension.Fpu) },

        // FILD
        { FildMw, new("fild", Fild.Mw, 0, IsaExtension.Fpu) },
        { FildMd, new("fild", Fild.Md, 0, IsaExtension.Fpu) },
        { FildMq, new("fild", Fild.Mq, 0, IsaExtension.Fpu) },

        // FINCSTP
        { Opcode.Fincstp, new("fincstp", Instruction.Fincstp._, 0, IsaExtension.Fpu) },

        // FINIT
        { Opcode.Finit, new("finit", Instruction.Finit._, 0, IsaExtension.Fpu) },

        // FIST / FISTP / FISTTP
        { FistMw, new("fist", Fist.Mw, 0, IsaExtension.Fpu) },
        { FistMd, new("fist", Fist.Md, 0, IsaExtension.Fpu) },
        { FistpMw, new("fistp", Fistp.Mw, 0, IsaExtension.Fpu) },
        { FistpMd, new("fistp", Fistp.Md, 0, IsaExtension.Fpu) },
        { FistpMq, new("fistp", Fistp.Mq, 0, IsaExtension.Fpu) },
        { FisttpMw, new("fisttp", Fisttp.Mw, 0, IsaExtension.Fpu) },
        { FisttpMd, new("fisttp", Fisttp.Md, 0, IsaExtension.Fpu) },
        { FisttpMq, new("fisttp", Fisttp.Mq, 0, IsaExtension.Fpu) },

        // FIXUPIMMPD
        { VfixupimmpdVxHxWxIbE128, new("vfixupimmpd", Fixupimmpd.VxHxWxIbE128, 0, Avx512_VL) },
        { VfixupimmpdVyHyWyIbE256, new("vfixupimmpd", Fixupimmpd.VyHyWyIbE256, 0, Avx512_VL) },
        { VfixupimmpdVzHzWzIbE512, new("vfixupimmpd", Fixupimmpd.VzHzWzIbE512, 0, Avx512_F) },

        // FIXUPIMMPS
        { VfixupimmpsVxHxWxIbE128, new("vfixupimmps", Fixupimmps.VxHxWxIbE128, 0, Avx512_VL) },
        { VfixupimmpsVyHyWyIbE256, new("vfixupimmps", Fixupimmps.VyHyWyIbE256, 0, Avx512_VL) },
        { VfixupimmpsVzHzWzIbE512, new("vfixupimmps", Fixupimmps.VzHzWzIbE512, 0, Avx512_F) },

        // FIXUPIMMSD
        { VfixupimmsdVxHxWxIbE, new("vfixupimmsd", Fixupimmsd.VxHxWxIbE, 0, Avx512_F) },

        // FIXUPIMMSS
        { VfixupimmssVxHxWxIbE, new("vfixupimmss", Fixupimmss.VxHxWxIbE, 0, Avx512_F) },

        // FLD / FLDx
        { FldMd, new("fld", Fld.Md, 0, IsaExtension.Fpu) },
        { FldMq, new("fld", Fld.Mq, 0, IsaExtension.Fpu) },
        { FldMt, new("fld", Fld.Mt, 0, IsaExtension.Fpu) },
        { FldSTi, new("fld", Fld.STi, 0, IsaExtension.Fpu) },
        { Opcode.Fld1, new("fld", Instruction.Fld1._, 0, IsaExtension.Fpu) },
        { Opcode.Fldl2t, new("fld", Instruction.Fldl2t._, 0, IsaExtension.Fpu) },
        { Opcode.Fldl2e, new("fld", Instruction.Fldl2e._, 0, IsaExtension.Fpu) },
        { Opcode.Fldpi, new("fld", Instruction.Fldpi._, 0, IsaExtension.Fpu) },
        { Opcode.Fldlg2, new("fld", Instruction.Fldlg2._, 0, IsaExtension.Fpu) },
        { Opcode.Fldln2, new("fld", Instruction.Fldln2._, 0, IsaExtension.Fpu) },
        { Opcode.Fldz, new("fld", Instruction.Fldz._, 0, IsaExtension.Fpu) },

        // FLDCW
        { FldcwMw, new("fldcw", Fldcw.Mw, 0, IsaExtension.Fpu) },

        // FLDENV
        { FldenvM, new("fldenv", Fldenv.M, 0, IsaExtension.Fpu) },

        #region FMA Add
        // FMADDnnnPD
        { Vfmadd132pdVxHxWxV128, new("vfmadd132pd", Fmadd132pd.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmadd132pdVyHyWyV256, new("vfmadd132pd", Fmadd132pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmadd132pdVxHxWxE128, new("vfmadd132pd", Fmadd132pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmadd132pdVyHyWyE256, new("vfmadd132pd", Fmadd132pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmadd132pdVzHzWzE512, new("vfmadd132pd", Fmadd132pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmadd213pdVxHxWxV128, new("vfmadd213pd", Fmadd213pd.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmadd213pdVyHyWyV256, new("vfmadd213pd", Fmadd213pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmadd213pdVxHxWxE128, new("vfmadd213pd", Fmadd213pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmadd213pdVyHyWyE256, new("vfmadd213pd", Fmadd213pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmadd213pdVzHzWzE512, new("vfmadd213pd", Fmadd213pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmadd231pdVxHxWxV128, new("vfmadd231pd", Fmadd231pd.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmadd231pdVyHyWyV256, new("vfmadd231pd", Fmadd231pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmadd231pdVxHxWxE128, new("vfmadd231pd", Fmadd231pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmadd231pdVyHyWyE256, new("vfmadd231pd", Fmadd231pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmadd231pdVzHzWzE512, new("vfmadd231pd", Fmadd231pd.VzHzWzE512, 0, Avx512_F) },

        // FMADDnnnPS
        { Vfmadd132psVxHxWxV128, new("vfmadd132ps", Fmadd132ps.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmadd132psVyHyWyV256, new("vfmadd132ps", Fmadd132ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmadd132psVxHxWxE128, new("vfmadd132ps", Fmadd132ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmadd132psVyHyWyE256, new("vfmadd132ps", Fmadd132ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmadd132psVzHzWzE512, new("vfmadd132ps", Fmadd132ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmadd213psVxHxWxV128, new("vfmadd213ps", Fmadd213ps.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmadd213psVyHyWyV256, new("vfmadd213ps", Fmadd213ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmadd213psVxHxWxE128, new("vfmadd213ps", Fmadd213ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmadd213psVyHyWyE256, new("vfmadd213ps", Fmadd213ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmadd213psVzHzWzE512, new("vfmadd213ps", Fmadd213ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmadd231psVxHxWxV128, new("vfmadd231ps", Fmadd231ps.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmadd231psVyHyWyV256, new("vfmadd231ps", Fmadd231ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmadd231psVxHxWxE128, new("vfmadd231ps", Fmadd231ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmadd231psVyHyWyE256, new("vfmadd231ps", Fmadd231ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmadd231psVzHzWzE512, new("vfmadd231ps", Fmadd231ps.VzHzWzE512, 0, Avx512_F) },

        // FMADDnnSD
        { Vfmadd132sdVxHxWxV, new("vfmadd132sd", Fmadd132sd.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfmadd132sdVxHxWxE, new("vfmadd132sd", Fmadd132sd.VxHxWxE, 0, Avx512_F) },
        { Vfmadd213sdVxHxWxV, new("vfmadd213sd", Fmadd213sd.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfmadd213sdVxHxWxE, new("vfmadd213sd", Fmadd213sd.VxHxWxE, 0, Avx512_F) },
        { Vfmadd231sdVxHxWxV, new("vfmadd231sd", Fmadd231sd.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfmadd231sdVxHxWxE, new("vfmadd231sd", Fmadd231sd.VxHxWxE, 0, Avx512_F) },

        // FMADDnnSS
        { Vfmadd132ssVxHxWxV, new("vfmadd132ss", Fmadd132ss.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfmadd132ssVxHxWxE, new("vfmadd132ss", Fmadd132ss.VxHxWxE, 0, Avx512_F) },
        { Vfmadd213ssVxHxWxV, new("vfmadd213ss", Fmadd213ss.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfmadd213ssVxHxWxE, new("vfmadd213ss", Fmadd213ss.VxHxWxE, 0, Avx512_F) },
        { Vfmadd231ssVxHxWxV, new("vfmadd231ss", Fmadd231ss.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfmadd231ssVxHxWxE, new("vfmadd231ss", Fmadd231ss.VxHxWxE, 0, Avx512_F) },
        #endregion

        #region FMA AddSub / SubAdd
        // FMADDSUBnnnPD
        { Vfmaddsub132pdVxHxWxV128, new("vfmaddsub132pd", Fmaddsub132pd.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmaddsub132pdVyHyWyV256, new("vfmaddsub132pd", Fmaddsub132pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmaddsub132pdVxHxWxE128, new("vfmaddsub132pd", Fmaddsub132pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmaddsub132pdVyHyWyE256, new("vfmaddsub132pd", Fmaddsub132pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmaddsub132pdVzHzWzE512, new("vfmaddsub132pd", Fmaddsub132pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmaddsub213pdVxHxWxV128, new("vfmaddsub213pd", Fmaddsub213pd.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmaddsub213pdVyHyWyV256, new("vfmaddsub213pd", Fmaddsub213pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmaddsub213pdVxHxWxE128, new("vfmaddsub213pd", Fmaddsub213pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmaddsub213pdVyHyWyE256, new("vfmaddsub213pd", Fmaddsub213pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmaddsub213pdVzHzWzE512, new("vfmaddsub213pd", Fmaddsub213pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmaddsub231pdVxHxWxV128, new("vfmaddsub231pd", Fmaddsub231pd.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmaddsub231pdVyHyWyV256, new("vfmaddsub231pd", Fmaddsub231pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmaddsub231pdVxHxWxE128, new("vfmaddsub231pd", Fmaddsub231pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmaddsub231pdVyHyWyE256, new("vfmaddsub231pd", Fmaddsub231pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmaddsub231pdVzHzWzE512, new("vfmaddsub231pd", Fmaddsub231pd.VzHzWzE512, 0, Avx512_F) },

        // FMADDSUBnnnPS
        { Vfmaddsub132psVxHxWxV128, new("vfmaddsub132ps", Fmaddsub132ps.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmaddsub132psVyHyWyV256, new("vfmaddsub132ps", Fmaddsub132ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmaddsub132psVxHxWxE128, new("vfmaddsub132ps", Fmaddsub132ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmaddsub132psVyHyWyE256, new("vfmaddsub132ps", Fmaddsub132ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmaddsub132psVzHzWzE512, new("vfmaddsub132ps", Fmaddsub132ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmaddsub213psVxHxWxV128, new("vfmaddsub213ps", Fmaddsub213ps.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmaddsub213psVyHyWyV256, new("vfmaddsub213ps", Fmaddsub213ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmaddsub213psVxHxWxE128, new("vfmaddsub213ps", Fmaddsub213ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmaddsub213psVyHyWyE256, new("vfmaddsub213ps", Fmaddsub213ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmaddsub213psVzHzWzE512, new("vfmaddsub213ps", Fmaddsub213ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmaddsub231psVxHxWxV128, new("vfmaddsub231ps", Fmaddsub231ps.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmaddsub231psVyHyWyV256, new("vfmaddsub231ps", Fmaddsub231ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmaddsub231psVxHxWxE128, new("vfmaddsub231ps", Fmaddsub231ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmaddsub231psVyHyWyE256, new("vfmaddsub231ps", Fmaddsub231ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmaddsub231psVzHzWzE512, new("vfmaddsub231ps", Fmaddsub231ps.VzHzWzE512, 0, Avx512_F) },

        // FMSUBADDnnnPD
        { Vfmsubadd132pdVxHxWxV128, new("vfmsubadd132pd", Fmsubadd132pd.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmsubadd132pdVyHyWyV256, new("vfmsubadd132pd", Fmsubadd132pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsubadd132pdVxHxWxE128, new("vfmsubadd132pd", Fmsubadd132pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsubadd132pdVyHyWyE256, new("vfmsubadd132pd", Fmsubadd132pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsubadd132pdVzHzWzE512, new("vfmsubadd132pd", Fmsubadd132pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmsubadd213pdVxHxWxV128, new("vfmsubadd213pd", Fmsubadd213pd.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmsubadd213pdVyHyWyV256, new("vfmsubadd213pd", Fmsubadd213pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsubadd213pdVxHxWxE128, new("vfmsubadd213pd", Fmsubadd213pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsubadd213pdVyHyWyE256, new("vfmsubadd213pd", Fmsubadd213pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsubadd213pdVzHzWzE512, new("vfmsubadd213pd", Fmsubadd213pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmsubadd231pdVxHxWxV128, new("vfmsubadd231pd", Fmsubadd231pd.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmsubadd231pdVyHyWyV256, new("vfmsubadd231pd", Fmsubadd231pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsubadd231pdVxHxWxE128, new("vfmsubadd231pd", Fmsubadd231pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsubadd231pdVyHyWyE256, new("vfmsubadd231pd", Fmsubadd231pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsubadd231pdVzHzWzE512, new("vfmsubadd231pd", Fmsubadd231pd.VzHzWzE512, 0, Avx512_F) },

        // FMSUBADDnnnPS
        { Vfmsubadd132psVxHxWxV128, new("vfmsubadd132ps", Fmsubadd132ps.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmsubadd132psVyHyWyV256, new("vfmsubadd132ps", Fmsubadd132ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsubadd132psVxHxWxE128, new("vfmsubadd132ps", Fmsubadd132ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsubadd132psVyHyWyE256, new("vfmsubadd132ps", Fmsubadd132ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsubadd132psVzHzWzE512, new("vfmsubadd132ps", Fmsubadd132ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmsubadd213psVxHxWxV128, new("vfmsubadd213ps", Fmsubadd213ps.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmsubadd213psVyHyWyV256, new("vfmsubadd213ps", Fmsubadd213ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsubadd213psVxHxWxE128, new("vfmsubadd213ps", Fmsubadd213ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsubadd213psVyHyWyE256, new("vfmsubadd213ps", Fmsubadd213ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsubadd213psVzHzWzE512, new("vfmsubadd213ps", Fmsubadd213ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmsubadd231psVxHxWxV128, new("vfmsubadd231ps", Fmsubadd231ps.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmsubadd231psVyHyWyV256, new("vfmsubadd231ps", Fmsubadd231ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsubadd231psVxHxWxE128, new("vfmsubadd231ps", Fmsubadd231ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsubadd231psVyHyWyE256, new("vfmsubadd231ps", Fmsubadd231ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsubadd231psVzHzWzE512, new("vfmsubadd231ps", Fmsubadd231ps.VzHzWzE512, 0, Avx512_F) },
        #endregion

        #region FMA Sub
        // FMSUBnnnPD
        { Vfmsub132pdVxHxWxV128, new("vfmsub132pd", Fmsub132pd.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmsub132pdVyHyWyV256, new("vfmsub132pd", Fmsub132pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsub132pdVxHxWxE128, new("vfmsub132pd", Fmsub132pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsub132pdVyHyWyE256, new("vfmsub132pd", Fmsub132pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsub132pdVzHzWzE512, new("vfmsub132pd", Fmsub132pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmsub213pdVxHxWxV128, new("vfmsub213pd", Fmsub213pd.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmsub213pdVyHyWyV256, new("vfmsub213pd", Fmsub213pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsub213pdVxHxWxE128, new("vfmsub213pd", Fmsub213pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsub213pdVyHyWyE256, new("vfmsub213pd", Fmsub213pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsub213pdVzHzWzE512, new("vfmsub213pd", Fmsub213pd.VzHzWzE512, 0, Avx512_F) },
        { Vfmsub231pdVxHxWxV128, new("vfmsub231pd", Fmsub231pd.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmsub231pdVyHyWyV256, new("vfmsub231pd", Fmsub231pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsub231pdVxHxWxE128, new("vfmsub231pd", Fmsub231pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsub231pdVyHyWyE256, new("vfmsub231pd", Fmsub231pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsub231pdVzHzWzE512, new("vfmsub231pd", Fmsub231pd.VzHzWzE512, 0, Avx512_F) },

        // FMSUBnnnPS
        { Vfmsub132psVxHxWxV128, new("vfmsub132ps", Fmsub132ps.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfmsub132psVyHyWyV256, new("vfmsub132ps", Fmsub132ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsub132psVxHxWxE128, new("vfmsub132ps", Fmsub132ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsub132psVyHyWyE256, new("vfmsub132ps", Fmsub132ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsub132psVzHzWzE512, new("vfmsub132ps", Fmsub132ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmsub213psVxHxWxV128, new("vfmsub213ps", Fmsub213ps.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfmsub213psVyHyWyV256, new("vfmsub213ps", Fmsub213ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsub213psVxHxWxE128, new("vfmsub213ps", Fmsub213ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsub213psVyHyWyE256, new("vfmsub213ps", Fmsub213ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsub213psVzHzWzE512, new("vfmsub213ps", Fmsub213ps.VzHzWzE512, 0, Avx512_F) },
        { Vfmsub231psVxHxWxV128, new("vfmsub231ps", Fmsub231ps.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfmsub231psVyHyWyV256, new("vfmsub231ps", Fmsub231ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfmsub231psVxHxWxE128, new("vfmsub231ps", Fmsub231ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfmsub231psVyHyWyE256, new("vfmsub231ps", Fmsub231ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfmsub231psVzHzWzE512, new("vfmsub231ps", Fmsub231ps.VzHzWzE512, 0, Avx512_F) },

        // FMSUBnnSD
        { Vfmsub132sdVxHxWxV, new("vfmsub132sd", Fmsub132sd.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfmsub132sdVxHxWxE, new("vfmsub132sd", Fmsub132sd.VxHxWxE, 0, Avx512_F) },
        { Vfmsub213sdVxHxWxV, new("vfmsub213sd", Fmsub213sd.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfmsub213sdVxHxWxE, new("vfmsub213sd", Fmsub213sd.VxHxWxE, 0, Avx512_F) },
        { Vfmsub231sdVxHxWxV, new("vfmsub231sd", Fmsub231sd.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfmsub231sdVxHxWxE, new("vfmsub231sd", Fmsub231sd.VxHxWxE, 0, Avx512_F) },

        // FMSUBnnSS
        { Vfmsub132ssVxHxWxV, new("vfmsub132ss", Fmsub132ss.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfmsub132ssVxHxWxE, new("vfmsub132ss", Fmsub132ss.VxHxWxE, 0, Avx512_F) },
        { Vfmsub213ssVxHxWxV, new("vfmsub213ss", Fmsub213ss.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfmsub213ssVxHxWxE, new("vfmsub213ss", Fmsub213ss.VxHxWxE, 0, Avx512_F) },
        { Vfmsub231ssVxHxWxV, new("vfmsub231ss", Fmsub231ss.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfmsub231ssVxHxWxE, new("vfmsub231ss", Fmsub231ss.VxHxWxE, 0, Avx512_F) },
        #endregion

        // FMUL / FMULP / FIMUL
        { FmulMd, new("fmul", Fmul.Md, 0, IsaExtension.Fpu) },
        { FmulMq, new("fmul", Fmul.Mq, 0, IsaExtension.Fpu) },
        { FmulST0STi, new("fmul", Fmul.ST0STi, 0, IsaExtension.Fpu) },
        { FmulSTiST0, new("fmul", Fmul.STiST0, 0, IsaExtension.Fpu) },
        { FmulpSTiST0, new("fmulp", Fmulp.STiST0, 0, IsaExtension.Fpu) },
        { FimulMd, new("fimul", Fimul.Md, 0, IsaExtension.Fpu) },
        { FimulMw, new("fimul", Fimul.Mw, 0, IsaExtension.Fpu) },

        #region FMA negated Add
        // FNMADDnnnPD
        { Vfnmadd132pdVxHxWxV128, new("vfnmadd132pd", Fnmadd132pd.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfnmadd132pdVyHyWyV256, new("vfnmadd132pd", Fnmadd132pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmadd132pdVxHxWxE128, new("vfnmadd132pd", Fnmadd132pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmadd132pdVyHyWyE256, new("vfnmadd132pd", Fnmadd132pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmadd132pdVzHzWzE512, new("vfnmadd132pd", Fnmadd132pd.VzHzWzE512, 0, Avx512_F) },
        { Vfnmadd213pdVxHxWxV128, new("vfnmadd213pd", Fnmadd213pd.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfnmadd213pdVyHyWyV256, new("vfnmadd213pd", Fnmadd213pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmadd213pdVxHxWxE128, new("vfnmadd213pd", Fnmadd213pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmadd213pdVyHyWyE256, new("vfnmadd213pd", Fnmadd213pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmadd213pdVzHzWzE512, new("vfnmadd213pd", Fnmadd213pd.VzHzWzE512, 0, Avx512_F) },
        { Vfnmadd231pdVxHxWxV128, new("vfnmadd231pd", Fnmadd231pd.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfnmadd231pdVyHyWyV256, new("vfnmadd231pd", Fnmadd231pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmadd231pdVxHxWxE128, new("vfnmadd231pd", Fnmadd231pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmadd231pdVyHyWyE256, new("vfnmadd231pd", Fnmadd231pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmadd231pdVzHzWzE512, new("vfnmadd231pd", Fnmadd231pd.VzHzWzE512, 0, Avx512_F) },

        // FNMADDnnnPS
        { Vfnmadd132psVxHxWxV128, new("vfnmadd132ps", Fnmadd132ps.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfnmadd132psVyHyWyV256, new("vfnmadd132ps", Fnmadd132ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmadd132psVxHxWxE128, new("vfnmadd132ps", Fnmadd132ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmadd132psVyHyWyE256, new("vfnmadd132ps", Fnmadd132ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmadd132psVzHzWzE512, new("vfnmadd132ps", Fnmadd132ps.VzHzWzE512, 0, Avx512_F) },
        { Vfnmadd213psVxHxWxV128, new("vfnmadd213ps", Fnmadd213ps.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfnmadd213psVyHyWyV256, new("vfnmadd213ps", Fnmadd213ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmadd213psVxHxWxE128, new("vfnmadd213ps", Fnmadd213ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmadd213psVyHyWyE256, new("vfnmadd213ps", Fnmadd213ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmadd213psVzHzWzE512, new("vfnmadd213ps", Fnmadd213ps.VzHzWzE512, 0, Avx512_F) },
        { Vfnmadd231psVxHxWxV128, new("vfnmadd231ps", Fnmadd231ps.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfnmadd231psVyHyWyV256, new("vfnmadd231ps", Fnmadd231ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmadd231psVxHxWxE128, new("vfnmadd231ps", Fnmadd231ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmadd231psVyHyWyE256, new("vfnmadd231ps", Fnmadd231ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmadd231psVzHzWzE512, new("vfnmadd231ps", Fnmadd231ps.VzHzWzE512, 0, Avx512_F) },

        // FNMADDnnSD
        { Vfnmadd132sdVxHxWxV, new("vfnmadd132sd", Fnmadd132sd.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfnmadd132sdVxHxWxE, new("vfnmadd132sd", Fnmadd132sd.VxHxWxE, 0, Avx512_F) },
        { Vfnmadd213sdVxHxWxV, new("vfnmadd213sd", Fnmadd213sd.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfnmadd213sdVxHxWxE, new("vfnmadd213sd", Fnmadd213sd.VxHxWxE, 0, Avx512_F) },
        { Vfnmadd231sdVxHxWxV, new("vfnmadd231sd", Fnmadd231sd.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfnmadd231sdVxHxWxE, new("vfnmadd231sd", Fnmadd231sd.VxHxWxE, 0, Avx512_F) },

        // FNMADDnnSS
        { Vfnmadd132ssVxHxWxV, new("vfnmadd132ss", Fnmadd132ss.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfnmadd132ssVxHxWxE, new("vfnmadd132ss", Fnmadd132ss.VxHxWxE, 0, Avx512_F) },
        { Vfnmadd213ssVxHxWxV, new("vfnmadd213ss", Fnmadd213ss.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfnmadd213ssVxHxWxE, new("vfnmadd213ss", Fnmadd213ss.VxHxWxE, 0, Avx512_F) },
        { Vfnmadd231ssVxHxWxV, new("vfnmadd231ss", Fnmadd231ss.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfnmadd231ssVxHxWxE, new("vfnmadd231ss", Fnmadd231ss.VxHxWxE, 0, Avx512_F) },
        #endregion

        #region FMA negated Sub
        // FNMSUBnnnPD
        { Vfnmsub132pdVxHxWxV128, new("vfnmsub132pd", Fnmsub132pd.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfnmsub132pdVyHyWyV256, new("vfnmsub132pd", Fnmsub132pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmsub132pdVxHxWxE128, new("vfnmsub132pd", Fnmsub132pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmsub132pdVyHyWyE256, new("vfnmsub132pd", Fnmsub132pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmsub132pdVzHzWzE512, new("vfnmsub132pd", Fnmsub132pd.VzHzWzE512, 0, Avx512_F) },
        { Vfnmsub213pdVxHxWxV128, new("vfnmsub213pd", Fnmsub213pd.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfnmsub213pdVyHyWyV256, new("vfnmsub213pd", Fnmsub213pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmsub213pdVxHxWxE128, new("vfnmsub213pd", Fnmsub213pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmsub213pdVyHyWyE256, new("vfnmsub213pd", Fnmsub213pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmsub213pdVzHzWzE512, new("vfnmsub213pd", Fnmsub213pd.VzHzWzE512, 0, Avx512_F) },
        { Vfnmsub231pdVxHxWxV128, new("vfnmsub231pd", Fnmsub231pd.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfnmsub231pdVyHyWyV256, new("vfnmsub231pd", Fnmsub231pd.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmsub231pdVxHxWxE128, new("vfnmsub231pd", Fnmsub231pd.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmsub231pdVyHyWyE256, new("vfnmsub231pd", Fnmsub231pd.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmsub231pdVzHzWzE512, new("vfnmsub231pd", Fnmsub231pd.VzHzWzE512, 0, Avx512_F) },

        // FNMSUBnnnPS
        { Vfnmsub132psVxHxWxV128, new("vfnmsub132ps", Fnmsub132ps.VxHxWxV128, 0, Avx, Fma) }, // ..132..
        { Vfnmsub132psVyHyWyV256, new("vfnmsub132ps", Fnmsub132ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmsub132psVxHxWxE128, new("vfnmsub132ps", Fnmsub132ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmsub132psVyHyWyE256, new("vfnmsub132ps", Fnmsub132ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmsub132psVzHzWzE512, new("vfnmsub132ps", Fnmsub132ps.VzHzWzE512, 0, Avx512_F) },
        { Vfnmsub213psVxHxWxV128, new("vfnmsub213ps", Fnmsub213ps.VxHxWxV128, 0, Avx, Fma) }, // ..213..
        { Vfnmsub213psVyHyWyV256, new("vfnmsub213ps", Fnmsub213ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmsub213psVxHxWxE128, new("vfnmsub213ps", Fnmsub213ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmsub213psVyHyWyE256, new("vfnmsub213ps", Fnmsub213ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmsub213psVzHzWzE512, new("vfnmsub213ps", Fnmsub213ps.VzHzWzE512, 0, Avx512_F) },
        { Vfnmsub231psVxHxWxV128, new("vfnmsub231ps", Fnmsub231ps.VxHxWxV128, 0, Avx, Fma) }, // ..231..
        { Vfnmsub231psVyHyWyV256, new("vfnmsub231ps", Fnmsub231ps.VyHyWyV256, 0, Avx, Fma) },
        { Vfnmsub231psVxHxWxE128, new("vfnmsub231ps", Fnmsub231ps.VxHxWxE128, 0, Avx512_VL) },
        { Vfnmsub231psVyHyWyE256, new("vfnmsub231ps", Fnmsub231ps.VyHyWyE256, 0, Avx512_VL) },
        { Vfnmsub231psVzHzWzE512, new("vfnmsub231ps", Fnmsub231ps.VzHzWzE512, 0, Avx512_F) },

        // FNMSUBnnSD
        { Vfnmsub132sdVxHxWxV, new("vfnmsub132sd", Fnmsub132sd.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfnmsub132sdVxHxWxE, new("vfnmsub132sd", Fnmsub132sd.VxHxWxE, 0, Avx512_F) },
        { Vfnmsub213sdVxHxWxV, new("vfnmsub213sd", Fnmsub213sd.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfnmsub213sdVxHxWxE, new("vfnmsub213sd", Fnmsub213sd.VxHxWxE, 0, Avx512_F) },
        { Vfnmsub231sdVxHxWxV, new("vfnmsub231sd", Fnmsub231sd.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfnmsub231sdVxHxWxE, new("vfnmsub231sd", Fnmsub231sd.VxHxWxE, 0, Avx512_F) },

        // FNMSUBnnSS
        { Vfnmsub132ssVxHxWxV, new("vfnmsub132ss", Fnmsub132ss.VxHxWxV, 0, Avx, Fma) }, // ..132..
        { Vfnmsub132ssVxHxWxE, new("vfnmsub132ss", Fnmsub132ss.VxHxWxE, 0, Avx512_F) },
        { Vfnmsub213ssVxHxWxV, new("vfnmsub213ss", Fnmsub213ss.VxHxWxV, 0, Avx, Fma) }, // ..213..
        { Vfnmsub213ssVxHxWxE, new("vfnmsub213ss", Fnmsub213ss.VxHxWxE, 0, Avx512_F) },
        { Vfnmsub231ssVxHxWxV, new("vfnmsub231ss", Fnmsub231ss.VxHxWxV, 0, Avx, Fma) }, // ..231..
        { Vfnmsub231ssVxHxWxE, new("vfnmsub231ss", Fnmsub231ss.VxHxWxE, 0, Avx512_F) },
        #endregion

        // FNOP
        { Opcode.Fnop, new("fnop", Instruction.Fnop._, 0, IsaExtension.Fpu) },

        // FPATAN
        { Opcode.Fpatan, new("fpatan", Instruction.Fpatan._, 0, IsaExtension.Fpu) },

        // FPCLASSPD
        { VfpclasspdKGqWxIbE128, new("vfpclasspd", Fpclasspd.KGqWxIbE128, 0, Avx512_VL, Avx512_DQ) },
        { VfpclasspdKGqWyIbE256, new("vfpclasspd", Fpclasspd.KGqWyIbE256, 0, Avx512_VL, Avx512_DQ) },
        { VfpclasspdKGqWzIbE512, new("vfpclasspd", Fpclasspd.KGqWzIbE512, 0, Avx512_F, Avx512_DQ) },

        // FPCLASSPS
        { VfpclasspsKGqWxIbE128, new("vfpclassps", Fpclassps.KGqWxIbE128, 0, Avx512_VL, Avx512_DQ) },
        { VfpclasspsKGqWyIbE256, new("vfpclassps", Fpclassps.KGqWyIbE256, 0, Avx512_VL, Avx512_DQ) },
        { VfpclasspsKGqWzIbE512, new("vfpclassps", Fpclassps.KGqWzIbE512, 0, Avx512_F, Avx512_DQ) },

        // FPCLASSSD
        { VfpclasssdKGqWxIbE, new("vfpclasssd", Fpclasssd.KGqWxIbE, 0, Avx512_F, Avx512_DQ) },

        // FPCLASSSS
        { VfpclassssKGqWxIbE, new("vfpclassss", Fpclassss.KGqWxIbE, 0, Avx512_F, Avx512_DQ) },

        // FPREM
        { Opcode.Fprem, new("fprem", Instruction.Fprem._, 0, IsaExtension.Fpu) },

        // FPTAN
        { Opcode.Fptan, new("fptan", Instruction.Fptan._, 0, IsaExtension.Fpu) },

        // FRNDINT
        { Opcode.Frndint, new("frndint", Instruction.Frndint._, 0, IsaExtension.Fpu) },

        // FRSTOR
        { FrstorM, new("frstor", Frstor.M, 0, IsaExtension.Fpu) },

        // FSAVE
        { FsaveM, new("fsave", Fsave.M, 0, IsaExtension.Fpu) },

        // FSCALE
        { Opcode.Fscale, new("fscale", Instruction.Fscale._, 0, IsaExtension.Fpu) },

        // FSIN
        { Opcode.Fsin, new("fsin", Instruction.Fsin._, 0, IsaExtension.Fpu) },

        // FSINCOS
        { Opcode.Fsincos, new("fsincos", Instruction.Fsincos._, 0, IsaExtension.Fpu) },

        // FSQRT
        { Opcode.Fsqrt, new("fsqrt", Instruction.Fsqrt._, 0, IsaExtension.Fpu) },

        // FST / FSTP
        { FstMd, new("fst", Fst.Md, 0, IsaExtension.Fpu) },
        { FstMq, new("fst", Fst.Mq, 0, IsaExtension.Fpu) },
        { FstSTi, new("fst", Fst.STi, 0, IsaExtension.Fpu) },
        { FstpMd, new("fstp", Fstp.Md, 0, IsaExtension.Fpu) },
        { FstpMq, new("fstp", Fstp.Mq, 0, IsaExtension.Fpu) },
        { FstpMt, new("fstp", Fstp.Mt, 0, IsaExtension.Fpu) },
        { FstpSTi, new("fstp", Fstp.STi, 0, IsaExtension.Fpu) },

        // FSTCW
        { FstcwMw, new("fstcw", Fstcw.Mw, 0, IsaExtension.Fpu) },

        // FSTENV
        { FstenvM, new("fstenv", Fstenv.M, 0, IsaExtension.Fpu) },

        // FSTSW
        { FstswMw, new("fstsw", Fstsw.Mw, 0, IsaExtension.Fpu) },
        { FstswAX, new("fstsw", Fstsw.AX, 0, IsaExtension.Fpu) },

        // FSUB / FSUBP / FISUB
        { FsubMd, new("fsub", Fsub.Md, 0, IsaExtension.Fpu) },
        { FsubMq, new("fsub", Fsub.Mq, 0, IsaExtension.Fpu) },
        { FsubST0STi, new("fsub", Fsub.ST0STi, 0, IsaExtension.Fpu) },
        { FsubSTiST0, new("fsub", Fsub.STiST0, 0, IsaExtension.Fpu) },
        { FsubpSTiST0, new("fsubp", Fsubp.STiST0, 0, IsaExtension.Fpu) },
        { FisubMd, new("fisub", Fisub.Md, 0, IsaExtension.Fpu) },
        { FisubMw, new("fisub", Fisub.Mw, 0, IsaExtension.Fpu) },

        // FSUBR / FSUBRP / FISUBR
        { FsubrMd, new("fsubr", Fsubr.Md, 0, IsaExtension.Fpu) },
        { FsubrMq, new("fsubr", Fsubr.Mq, 0, IsaExtension.Fpu) },
        { FsubrST0STi, new("fsubr", Fsubr.ST0STi, 0, IsaExtension.Fpu) },
        { FsubrSTiST0, new("fsubr", Fsubr.STiST0, 0, IsaExtension.Fpu) },
        { FsubrpSTiST0, new("fsubrp", Fsubrp.STiST0, 0, IsaExtension.Fpu) },
        { FisubrMd, new("fisubr", Fisubr.Md, 0, IsaExtension.Fpu) },
        { FisubrMw, new("fisubr", Fisubr.Mw, 0, IsaExtension.Fpu) },

        // FTST
        { Opcode.Ftst, new("ftst", Instruction.Ftst._, 0, IsaExtension.Fpu) },

        // FUCOM / FUCOMP / FUCOMPP
        { FucomSTi, new("fucom", Fucom.STi, 0, IsaExtension.Fpu) },
        { FucompSTi, new("fucomp", Fucomp.STi, 0, IsaExtension.Fpu) },
        { Opcode.Fucompp, new("fucompp", Instruction.Fucompp._, 0, IsaExtension.Fpu) },

        // FXAM
        { Opcode.Fxam, new("fxam", Instruction.Fxam._, 0, IsaExtension.Fpu) },

        // FXCH
        { FxchSTi, new("fxch", Fxch.STi, 0, IsaExtension.Fpu) },

        // FXRSTOR / FXRSTOR64
        { FxrstorM, new("fxrstor", Fxrstor.M, 0, Fxsr) },
        { Fxrstor64M, new("fxrstor64", Fxrstor64.M, 0, Fxsr) },

        // FXSAVE / FXSAVE64
        { FxsaveM, new("fxsave", Fxsave.M, 0, Fxsr) },
        { Fxsave64M, new("fxsave64", Fxsave64.M, 0, Fxsr) },

        // FXTRACT
        { Opcode.Fxtract, new("fxtract", Instruction.Fxtract._, 0, IsaExtension.Fpu) },

        // FYL2X
        { Opcode.Fyl2x, new("fyl2x", Instruction.Fyl2x._, 0, IsaExtension.Fpu) },

        // FYL2XP1
        { Opcode.Fyl2xp1, new("fyl2xp1", Instruction.Fyl2xp1._, 0, IsaExtension.Fpu) },
        #endregion
    });
}
